### ISSUE TITLE
JTable having design problem in IE.

### ISSUE THREAD

**Issue by ranjan653** [hikalkan/jtable#1141]
Dear Sir,

              Kindly solve the JTable design problem In IE.Functionality is ok.But having design problem.  do the need full.

Ranjan Kumar Gochhayat
Sr. Java Consultant
Sapi Labs Pvt. Ltd
India

**Comment by sandeepmeenuga** [comment]
In Chrome data loading of 500 records is taking consistently 4 or 5 seconds, but same count of records loading in IE 10 or 11 taking almost 20 seconds. Can you guide me how to reduce the amount of time in IE 10 or 11.
