### ISSUE TITLE
Got nothing right after added options

### ISSUE THREAD

**Issue by viking58** [hikalkan/jtable#1602]
Hi,

I tried your jTable and its really perfect but I already have some problem when I try to using it.

I have table that already some data from MySQL database.
one of my fields name `cname` I want to have dropdown option when I try to edit it.

cname: {
		title: 'Category',
		width: '25%'
}

when I use above code it read from database perfectly and show the data 
but when I try to add options from my database It show nothing on loading
cname: {
						title: 'Category',
						width: '25%',
						options: <?php
							$res1=$mysqli->query("SELECT * FROM `cats`");
							while($row=$res1->fetch_array()){
										$options[$row['id']] = $row['cname'];
								}
								echo json_encode($options);
                                             ?>
},

its amazing because on my html source code it got data properly from database:
cname: {
						title: 'Category',
						width: '25%',
						defaultValue : 'hello',
						options: {"1":"aaa","2":"bbb"}					},

 and when I try to edit dropdown showed and by click on save data showed on `cname` field! and my database updated successfully !!!

Please help me on this issue
Thanks
Nick

**Comment by viking58** [comment]
I just wonder if anyone can help me on this issue!

**Comment by denhsieh** [comment]
make sure your json string looks like this, I'm currently learning how to do this too, also this thread might help you out https://github.com/hikalkan/jtable/issues/557

{"Result":"OK","Options":[{"DisplayText":"Option 1 Text","Value":"Option 1 Value"},{"DisplayText":"Option 2 Text","Value":"Option 2 Value"},{"DisplayText":"Option 3 Text","Value":"Option 3 Value"}]}

**Comment by viking58** [comment]
I just change json output as you said 

its now :
cname: {
	title: 'Category',
	width: '25%',
	options: {"Result":"OK","Options":[{"DisplayText":"1","Value":"aaa"},{"DisplayText":"2","Value":"bbb"}]}
},

But still show nothing also now when i click on "quick edit" button it show something wired!!
Select options are these two items!!!
1- OK
2- [object Object],[object Object]

**Comment by denhsieh** [comment]
What does your html code look like?

**Comment by viking58** [comment]
Here is all the codes base of define a URL

Main file:
       <section class="welly group"> 
       <div class="table-responsive">
          <div id="MyPosts" style="width:90%;margin:auto;overflow:hidden;"></div>
          <div id="addnew"><a href="postmaker.php?pid=newpost">+ Add New</a></div>
	<script type="text/javascript">

		$(document).ready(function () {
		    //Prepare jTable
			$('#MyPosts').jtable({
				title: 'Blog Posts',
				paging: true,
				pageSize: 4,
				sorting: true,
				defaultSorting: 'Name ASC',
				actions: {
					listAction: 'getposts.php?ac=list',
					
					updateAction: 'getposts.php?ac=update',
					deleteAction: 'getposts.php?ac=delete'
				},
				fields: {
					id: {
						key: true,
						create: false,
						edit: false,
						list: false
					},
					subject: {
						title: 'Posts Subject',
						width: '40%'
					},
					cname: {
						title: 'Category',
						width: '25%',
						options: 'getposts.php?ac=getcats'
							},
					PDate: {
						title: 'Post Date',
						width: '30%',
						create: false,
						edit: false
					},
					MyRecord:{
						title: '...',
						display: function (data) {
									return '<b><a href="postmaker.php?pid='+data.record.id+'"><img src="images/edit.png"  alt="Edit" /></a></b>';
								},
						width:'5%',
						edit: false,
						sorting: false	
						
					}
					
				},
				
			});

			//Load person list from server
			$('#MyPosts').jtable('load');
			

		});

	</script>
	
           
          </div>
  	   </section>
    </div>


PHP getposts.php?ac=getcats Code:

elseif($_GET[ac]=="getcats"){
			$res1=$mysqli->query("SELECT * FROM `cats`");
			if($res1->num_rows!=0){
			$rows = array();						
			while($row=$res1->fetch_array()){
						$eil = array();
						$eil[DisplayText] = $row[1];
						$eil[Value] = $row[0];
						$rows[] = $eil;
				}
			}
			$jTableResult = array();
			$jTableResult['Result'] = "OK";
			$jTableResult['Options'] = $rows;
			print json_encode($jTableResult);
}

That make this code:

{"Result":"OK","Options":[{"DisplayText":"aaa","Value":"1"},{"DisplayText":"bbb","Value":"2"}]}

And here is my screen shot:

![screen](https://cloud.githubusercontent.com/assets/10344175/5749201/d7eccf60-9c5b-11e4-9662-1552cdf89926.jpg)

**Comment by denhsieh** [comment]
I noticed an extra comma at the end of fields definition, other than that your options look like mine so I don't know why it's not showing up..

**Comment by viking58** [comment]
its strange but with or without that comma still I got nothing!!!!

Beside I can see all Category's options when I click on quick edit button!!!
![screen](https://cloud.githubusercontent.com/assets/10344175/5791792/25bded08-9f06-11e4-97cd-3ea503776d73.jpg)

**Comment by peterboccia** [comment]
You need to use the Category ID (the value in the options).

Cheers

**Comment by viking58** [comment]
now after I reverse our php file form 
```
while($row=$res1->fetch_array()){
						$eil = array();
						$eil[DisplayText] = $row[1];
						$eil[Value] = $row[0];
						$rows[] = $eil;
				}
			}
```
to
```
while($row=$res1->fetch_array()){
						$eil = array();
						$eil[DisplayText] = $row[0];
						$eil[Value] = $row[1];
						$rows[] = $eil;
				}
			}
```
  it show the field on Category column but it show numbers on category field
and also option on quick edit
![1](https://cloud.githubusercontent.com/assets/10344175/5792277/108a9768-9f26-11e4-8470-ca1c5fead783.jpg)

![2](https://cloud.githubusercontent.com/assets/10344175/5792280/21883002-9f26-11e4-9ec1-e85063c6ff0f.jpg)

and when I try to change category field for a row on quick edit it will try to put category string instead of ID

beside showing just ID number on category field is really inappropriate for people whom watching this table!!

**Comment by peterboccia** [comment]
Have you read my comment?
Your first php function for the options was good, but to show up the display text also in the grid, you should use not the "cname" but the "cid" or what you have named for the categoryid! you need the ID in the grid field:
```
 // NOT cname: {
cid: {
                        title: 'Category',
                        width: '25%',
                        options: 'getposts.php?ac=getcats'
                            },
```

Hope this helps.

**Comment by viking58** [comment]
thanks buddy

**Comment by peterboccia** [comment]
You welcome, good to know it helps.
