### ISSUE TITLE
Refresh table Data

### ISSUE THREAD

**Issue by oabrego** [hikalkan/jtable#1619]
Hi everyone, i hope someone could help me. I have an asp.net application with linq to sql and jtable. The problem is in the moment when insert a new record, the record is saved in the database, but it's not reflected in jtable till close the application and reopen it.

I tried to clear cache, refresh the jtable, refresh the datacontext of linq to sql, but nothing.

What can i do?.
Thanks.

**Comment by peterboccia** [comment]
Can you post some code please?
Do you call the 'reload' method after the insert? http://jtable.org/ApiReference/Methods#met-reload

**Comment by oabrego** [comment]
With this code  insert in the data base,  i  have a refresh button in the jtable, and i try call the datacontext after and before insert but doesn't work till close the session and reopen it 

using (CostosCotizacionesDataContext dbCotizam = new CostosCotizacionesDataContext())
                {                   
                    CostosCotizaciones record = new CostosCotizaciones(); //SQL
                    decimal fnlftes = 0;
                    if (ViewState["FinalFletes"] != null)
                    {
                        fnlftes = (decimal)ViewState["FinalFletes"];
                    }
                    record.no_cotizacion = c_NoCot;              
                    record.version = Convert.ToInt16(N_Ver);                
                    record.id_cte = Convert.ToInt32(ddlCliente.SelectedValue.ToString());                 
                    record.unidadNegocio = Convert.ToInt32(ddlUnidadNegocio.SelectedValue.ToString());                  
                    record.moneda = Convert.ToInt32(ddlMoneda.SelectedValue.ToString());                 
                    record.tipo_cambio = Convert.ToDecimal(txtParidad.Text);               
                    record.empleado_cotizo = lblTest.Text;                    
                    record.empleado_vendedor = ddlVendedor.SelectedValue.ToString();                   
                    record.id_contacto = Convert.ToInt32(ddlContacto.SelectedValue.ToString());                   
                    record.fecha = Convert.ToDateTime(txtFecha.Text);                   
                    record.id_ciudad = Convert.ToInt32(ddlUbicacion.SelectedValue.ToString());                   
                    record.id_estado = GetIdState(Convert.ToInt32(ddlUbicacion.SelectedValue.ToString()));                    
                    record.id_pais = GetIdPais(Convert.ToInt32(ddlUbicacion.SelectedValue.ToString()));                    
                    record.proyecto = ddlProyectoPrincipal.SelectedItem.ToString();                   
                    record.material = fnlftes - fnlftes;                    
                    record.flete = fnlftes;                  
                    record.estatus = "COT";                  
                    record.tasaIVA = 0;                    
                    record.zona = zona;                   
                    record.tipo_cotizacion = C_tipo;                    
                    record.imprimir_peso = chkImpPeso.Checked;                   
                    record.imprimir_precio = chkImpPu.Checked;                  
                    record.idioma = Convert.ToChar(rbtlIdioma.SelectedValue.ToString());                  
                    if (chkAditiva.Checked == true)                    {
                        record.seguimiento = Convert.ToChar("A");                       
                    }
                    else
                    {
                        record.seguimiento = Convert.ToChar("N");                       
                    }
                    record.observaciones = "";
                    if (txtAlias.Text == string.Empty)
                    {
                        record.alias = "";                      
                    }
                    else
                    {
                        record.alias = txtAlias.Text.ToUpper();                       
                    }
					con.sp = "sp_returntableidentity";
                    con.spParametros.Add("@tabla", System.Data.SqlDbType.VarChar, 50).Value = "costos_tm_cotizaciones";
                    con.spParametros.Add("@identidad", System.Data.SqlDbType.Int, 4).Direction = System.Data.ParameterDirection.ReturnValue;
                    N_IdCot = Convert.ToInt32(con.execSP("@identidad").ToString());                                      
                    record.id_cotizacion = N_IdCot;  //GET THE IDENTITY BEFORE INSERT
					
					MemoryDataSource mds = new MemoryDataSource(); //RELOAD ALL DATA CONTEXT IN THE APP
                    mds.costoscotizaciones.Add(record);
					
					dbCotizam.costos_tm_cotizaciones.InsertOnSubmit(rec);                  
                    dbCotizam.SubmitChanges(); //THE DATA IT'S INSERTED ON THE DB
					
					//TRY TO REFRESH THE DATA CONTEXT
					dbCotizam.Refresh(System.Data.Linq.RefreshMode.OverwriteCurrentValues, dbCotizam.costos_tm_cotizaciones);
                    dbCotizam.Refresh(System.Data.Linq.RefreshMode.OverwriteCurrentValues, rec);
					//CLEAR THE CACHE
					dbCotizam.GetType().InvokeMember("ClearCache", System.Reflection.BindingFlags.Instance |
                        System.Reflection.BindingFlags.Public |
                        System.Reflection.BindingFlags.NonPublic |
                        System.Reflection.BindingFlags.InvokeMethod, null, dbCotizam, null);
						
	}
