### ISSUE TITLE
Datepicker on formCreated

### ISSUE THREAD

**Issue by tom-methot** [hikalkan/jtable#1628]
Hi,
I'm trying to set maxDate on datePicker so i tried this  but its not working  

formCreated: function (event, data){
      data.form.find('input[name="Debut"]').datepicker({
		maxDate: 0
      });
},

**Comment by peterboccia** [comment]
I think that the problem it's not the form or the input but your call to datepicker.
Give a look at API:
http://jqueryui.com/datepicker/#min-max

**Comment by tom-methot** [comment]
there is the solution i found :

data.form.find('input[name="Debut"]').datepicker("option", "maxDate", "Today");
