### ISSUE TITLE
Problem with two date in same row

### ISSUE THREAD

**Issue by Franaccia** [hikalkan/jtable#1653]
I have two item in a row of date type. 
When attempt to edit this field datepicker refers every the first item and I don't change second filed value.
This is my html page, can you help me.
thank a lot

@model IEnumerable<Cinestar.Models.MovieWeek>

@Scripts.Render("~/bundles/jqueryui")
<script>
    $(function () {
        $("#datainizio").datepicker($.datepicker.regional['it']);
    });
</script>

<div class="filtering">
    <form>
        <div class="ui-widget">
            <label>Data inizio: @Html.TextBox("datainizio") </label>
            
            <button type="submit" id="LoadRecordsButton" class="RicercaButton">Cerca</button>
            <button type="reset" id="ResetRecordsButton" class="RicercaButton">Cancella</button>

        </div>
    </form>
</div>

@Html.Hidden("maxdata")

<div id="MovieWeekTableContainer">
</div>
@section Scripts {

    <script type="text/javascript">

    $(document).ready(function () {

        $('#MovieWeekTableContainer').jtable({
            title: 'Settimana cinematografica',
            paging: true,
            pageSize: 10,
            sorting: true,
            defaultSorting: 'StartDate DESC',

            actions: {
                listAction: '@Url.Action("SearchMovieWeekList")',
                deleteAction: '@Url.Action("DeleteMovieWeek")',
                updateAction: '@Url.Action("UpdateMovieWeek")',
                createAction: '@Url.Action("CreateMovieWeek")'
                },
                toolbar: {
                    items: [{
                        tooltip: 'Clicca qui per esportare questa tabella in Excel',
                        text: 'Export to Excel',
                        icon: '../Content/images/excel.png',
                        click: function (e) {

                            var form = $('form');
                            form.attr('action', '../MovieWeek/Export');
                            form.attr('method', 'POST');
                            form.submit();
                        }

                    }]
                },
                fields: {
                    Id: {
                        key: true,
                        create: false,
                        edit: false,
                        list: false
                    },
                    StartDate: {
                        title: 'Data inizio',
                        type:"date",
                        displayFormat:"dd/mm/yy",
                        width: '50%',
                        inputClass: 'validate[required]'
                    },
                    EndDate: {
                        title: 'Data fine',
                        type: "date",
                        displayFormat: "dd/mm/yy",
                        width: '50%',
                        inputClass: 'validate[required]'
                    }

                },
                //Initialize validation logic when a form is created
                formCreated: function (event, data) {
                   
                    if (data.formType == "create")
                    {
                        
                        var tmp = $("#maxdata").val();
                        
                        var days = 6;
                        var date = $.datepicker.parseDate('dd/mm/yy', tmp);
                       

                        data.form.find("#Edit-StartDate").datetimepicker("setDate", date);
                        
                        date.setDate(date.getDate() + days);
                        data.form.find("#Edit-EndDate").datetimepicker("setDate", new Date());
                                               
                    }

                    data.form.validationEngine();
                },
                //Validate form when it is being submitted
                formSubmitting: function (event, data) {
                    data.form.find('input[name="EndDate"]').removeAttr('class');
                   // data.form.find('input[name="EndDate"]').addClass('hasDatepicker');
                    data.form.find('input[name="EndDate"]').addClass('validate[required,date,dalal,' + data.form.find('#Edit-StartDate').val() + ']');
                    
                    return data.form.validationEngine('validate');
                },
                //Dispose validation logic when form is closed
                formClosed: function (event, data) {
                   
                    data.form.validationEngine('hide');
                    data.form.validationEngine('detach');
                },
                recordsLoaded: function (event, data) {
                    
                    $("#maxdata").val(data.serverResponse.MaxData )
                }
            });

            //Re-load records when user click 'load records' button.
            $('#LoadRecordsButton').click(function (e) {
                e.preventDefault();
                $('#MovieWeekTableContainer').jtable('load', {
                    data: $('#datainizio').val()
                });
            });

            //Load all records when page is first shown
            $('#LoadRecordsButton').click();

            //Re-load records when user click 'load records' button.
            $('#ResetRecordsButton').click(function (e) {
                e.preventDefault();

                $('#datainizio').val("");

            });

        });

    </script>
}

**Comment by sheryever** [comment]
@Franaccia 

You should not use `type:'date'` when you are setup datetimepicker yourself. When we use `type:'date'`, jtable attach jquery datepicker with that field.

**Comment by Franaccia** [comment]
I use type:date and remove this code:

if (data.formType == "create")
                {

                    var tmp = $("#maxdata").val();

                    var days = 6;
                    var date = $.datepicker.parseDate('dd/mm/yy', tmp);


                    data.form.find("#Edit-StartDate").datetimepicker("setDate", date);

                    date.setDate(date.getDate() + days);
                    data.form.find("#Edit-EndDate").datetimepicker("setDate", new Date());

                }
but my date don't work.
the problem is that the EndDate is'nt never update, only StartDate is update when I click on calendar.

**Comment by Franaccia** [comment]
Sorry
I include two js file for jquery.

Now it's ok

Thankyou
