### ISSUE TITLE
Clear table data.

### ISSUE THREAD

**Issue by Daemon22** [hikalkan/jtable#1671]
Hello,
Is there a way to clear all table rows (locally)?

**Comment by sheryever** [comment]
@Daemon22 

there is no proper way. You can use `$('#StudentTableContainer').data('hikJtable')._removeAllRows()` but your paging will remain same.

**Comment by Daemon22** [comment]
Hi,
Thanks, I have managed to achieve that by adding this to the public methods:

removeAllRows: function() {
            this._removeAllRows();
},

And then I can call $("#StudentTableContainer").jtable("removeAllRows");

Thanks allot.
