### ISSUE TITLE
How to allow options and user input at the same time?

### ISSUE THREAD

**Issue by niushun** [hikalkan/jtable#1739]
The demo shows the UI that can allow the selection from a list of cities. What if the user wants to enter something which is not in the list? How to achieve that? Thanks.

**Comment by niushun** [comment]
I tried by using "dependsOn" like below, but not working.

City: {
  title: 'City',
  options: ['New York', 'Chicago', 'other']
},
OtherCity: {
  list: false,
  title: 'Other City',
  dependsOn: 'City',
  type: function (data) {
    if (data.dependedValues.City == 'other') {
      return 'text';
    }
    return 'hidden';
  }
}

**Comment by Kostya5** [comment]
May be will possible use jQuery autocomplete widget?
http://jqueryui.com/autocomplete/

just add jtable event
```javascript
formCreated: function (event, data) {
	data.form.find('[name=City]').autocomplete({
		source: ['New York', 'Chicago', 'other']
	});
}

**Comment by niushun** [comment]
Works beautifully, thanks a lot!
