### ISSUE TITLE
How to render Jtable after delete ??

### ISSUE THREAD

**Issue by snopbear** [hikalkan/jtable#1755]
First of all i congratulate you for you awesome work .. my issue  Mr: Kalkan ,  i disable all edit and delete buttons  except the last record for business conditions  by this snippet of code 

                rowInserted: function (event, data) {
                    //After child row loads. Check if your info and remove the edit/delete buttons if needed
                     
                    if (data.record.EXTRACT_NUM !== EXTRACT_Max_NUM || data.record.IS_PAID !== 0) {
                        data.row.find('.jtable-edit-command-button').hide();
                        data.row.find('.jtable-delete-command-button').hide();
                        data.row.find('.viewHref').hide();
                        
                    }

                },

and it works fine ...  but the problem is  when i delete the last record " no render " at all i need to refresh the page to reload  Jtable to show edit & delete button for the last record in jtable  ---- i tried $('#ProjectContainer').jtable('reload'); in 

- recordDeleted  but nothing at all

**Comment by hikalkan** [comment]
Hi,

Thanks a lot.

reload should work normally. But if you don't change EXTRACT_Max_NUM, then 'if' condition always will be true. Are you changing this value after delete?

Also, if always it will be the last line, you can implement it via some custom javascript/jquery code to find the last row of the table and show buttons after each delete.

**Comment by snopbear** [comment]
Thanks , Mr: hikalkan for your replay .. i tried to change EXTRACT_Max_NUM in  - recordDeleted
and recordAdded and get the result i have been searching for .. thanks for your great work , good day
