### ISSUE TITLE
Paging arrows don't show on production site

### ISSUE THREAD

**Issue by kwalkerk** [hikalkan/jtable#1758]
When developing my app using jTable, I get the nice paging arrows(<< < 1,2,3 > >>) in the left of the footer.  However when I publish my site to the production server they do not show. Neither does the 'Go to page' nor the 'Showing....'

Any ideas what's going on?

**Comment by hikalkan** [comment]
Have you checked if there is a problem by loading jtable's css file? Check it on Chrome's Dev Console and Network communication.

**Comment by kwalkerk** [comment]
jtable.min.css and
table_basic.css are loaded

looks like table_basic.less is not loaded

**Comment by hikalkan** [comment]
What's table_basic? It's not related to jTable. Can you share screenshot to see how paging is damaged.

**Comment by kwalkerk** [comment]
I modified the previous post , it should have said jtable_basic.css.  

below is screenshot 

![screen shot 2015-06-25 at 12 27 56 pm](https://cloud.githubusercontent.com/assets/488547/8359644/acf27a40-1b35-11e5-9dfe-6bae3be3ac23.png)

**Comment by kwalkerk** [comment]
Don't know if this helps or confuses but....

I set up a test to have the table load without directly setting the filter, just using the default values in the controller method which gets the data.  When I do that the footer is properly displayed.  However when I send the parameter by using
```javascript
$('#LoadRecordsButton').click(function (e) {
            e.preventDefault();
            $('#FeedTableContainer').jtable('load', {
                feedFilter:$('#SelectedSubject').val()
                
            });
        });
```
the paging display goes away and is as in the image above

**Comment by kwalkerk** [comment]
Another issue:  the TotalRecord count does not display properly either in the dev or live site

**Comment by kwalkerk** [comment]
I did a refresh of the .net environment on the server and this problem went away.
Thanks
