### ISSUE TITLE
Fill object json in table

### ISSUE THREAD

**Issue by quangkha91** [hikalkan/jtable#1766]
Hello all!
   I have a section code:
           var str = "{\"Result\":\"OK\",\"Record\":[{\"StudenId\":\"1\",\"Name\":\"KhaNQ\",\"EmailAddress\":\"dfssss@hotmail.com\",\"Gender\":\"M\",\"City\":\"1\",\"RecordDate\":\"10/11/1991\"}";
            var obj = jQuery.parseJSON(str);
            $('#StudentTableContainer').jtable({
                title: 'The Student List',
                   actions: {
                    listAction: obj,
                  .................

but it not view data in table. i don't know it issues, please,explain with me.
Thanks all.

**Comment by hikalkan** [comment]
See http://jtable.org/ApiReference/Actions#act-listAction

It should be similar like that:

<pre>listAction: function (postData, jtParams) {
    return {
        "Result": "OK",
        "Records": [
            { "StudentId": 39, "ContinentalId": 1, "CountryId": 18, "CityId": 55, "Name": "Agatha Garcia", "EmailAddress": "agatha.garcia@jtable.org", "Password": "123", "Gender": "F", "BirthDate": "\/Date(-1125111600000)\/", "About": "", "Education": 2, "IsActive": true, "RecordDate": "\/Date(1369083600000)\/" },
            { "StudentId": 61, "ContinentalId": 4, "CountryId": 1, "CityId": 1, "Name": "Agatha Lafore", "EmailAddress": "agatha.lafore@jtable.org", "Password": "123", "Gender": "F", "BirthDate": "\/Date(1017694800000)\/", "About": "", "Education": 3, "IsActive": true, "RecordDate": "\/Date(1393192800000)\/" }],
        "TotalRecordCount": 2
    };
}</pre>

**Comment by quangkha91** [comment]
Thank you very much hikalkan!

**Comment by ssriram30** [comment]
can i assign above structure in variable and use instead of that???

**Comment by sandeepmeenuga** [comment]
My issue is like this only, but want to send the data rather than taking.
Can you suggest me the way to send json data in ajax post request.
