### ISSUE TITLE
Geocomplete

### ISSUE THREAD

**Issue by kobonet** [hikalkan/jtable#1779]
I am trying to add geo-complete (Geocoding and Places Autocomplete) to an address field however I'm not able to make it work. I looked at the console and I can see prediction coming from Google but nothing is showing up as dropdown.

Following is the code I used and I've attached it to the field "Street" using formCreated.
<script src="scripts/jquery.geocomplete.js"></script>

                formCreated(event, data) {
                    data.form.find('input[name=Street]').geocomplete();
                }

Any help is appreciated!

**Comment by QuentinRillet** [comment]
Hello,
I just tested the function and with me everything works. Do you have error messages in your console?

Test:
==
formCreated: function (event, data) {
     $("#Edit-Street").geocomplete();
}

**Comment by kobonet** [comment]
There is no error in the console. I can see the placeholder text in the input box but no drop down is populating. I'm using the following scripts:

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
<script src="scripts/jquery-ui-1.8.16.custom.min.js" type="text/javascript"></script>
<script src="scripts/jtable/jquery.jtable.js" type="text/javascript"></script>
<script src="https://maps.googleapis.com/maps/api/js?v=3&libraries=places></script>
<script src="scripts/jquery.geocomplete.js"></script>

jTable 2.0.0

Could this be a version mismatch? Which version are you testing with?

**Comment by QuentinRillet** [comment]
I used:
* jquery-1.11.3.js
* "http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"
* jquery.geocomplete.js
* jTable 2.4 
* jQuery UI 1.11.4

![geo](https://cloud.githubusercontent.com/assets/6837604/8826704/a70ecd78-3088-11e5-891d-9de602121233.png)

**Comment by kobonet** [comment]
I've upgraded jTable, jquery and jQuery UI to the same version as yours and it now works perfectly. Thanks for your input.
