### ISSUE TITLE
New version jTable

### ISSUE THREAD

**Issue by QuentinRillet** [hikalkan/jtable#1782]
Hello hikalkan,
I just saw that you will regain jtable project. I myself resumed this project and I wanted to share my work if you wanted to use it to complement the main project.
Best Regards, Rillet Quentin.

https://github.com/QuentinRillet/jtable.git

**Comment by arvinaban** [comment]
can your version support passing two parameters to the "input: function" part?

**Comment by hikalkan** [comment]
Thank you very much @QuentinRillet 
I'll contact with you :)

**Comment by QuentinRillet** [comment]
To @arvinaban : Sorry it can't.
