### ISSUE TITLE
Greek localization file

### ISSUE THREAD

**Issue by nouvakis** [hikalkan/jtable#1797]
jquery.jtable.el.js

/*
    jTable localization file for 'Greek' language.
    Author: Nouvakis Petros
*/
(function ($) {

    $.extend(true, $.hik.jtable.prototype.options.messages, {
        serverCommunicationError: 'Παρουσιάστηκε σφάλμα στην προσπάθεια σύνδεσης στο διακομιστή.',
        loadingMessage: 'φορτώνονται οι εγγραφές...',
        noDataAvailable: 'Δεν υπάρχουν δεδομένα',
        addNewRecord: 'Νέα εγγραφή',
        editRecord: 'Διόρθωση',
        areYouSure: 'Είστε σίγουρος;',
        deleteConfirmation: 'Η εγγραφή θα διαγραφεί. Να προχωρήσω;',
        save: 'Αποθήκευση',
        saving: 'αποθηκεύονται οι εγγραφές...',
        cancel: 'Άκυρο',
        deleteText: 'Διαγραφή',
        deleting: 'Διαγράφονται εγγραφές...',
        error: 'ΛΑΘΟΣ',
        close: 'Κλείσιμο',
        cannotLoadOptionsFor: 'Δεν είναι δυνατή η φόρτωση επιλογών για το πεδίο {0}',
        pagingInfo: 'Εμφανίζονται {0} - {1} από {2}',
        canNotDeletedRecords: 'Δεν είναι δυνατή η διαγραφή {0} από {1}',
        deleteProggress: 'Διαγράφεται {0} από {1}...',
        pageSizeChangeLabel: 'Εγγραφές ανά σελίδα',
        gotoPageLabel: 'Πήγαινε στη σελίδα'
    });

})(jQuery);

**Comment by hikalkan** [comment]
Thanks a lot.
