### ISSUE TITLE
cannot save html tags

### ISSUE THREAD

**Issue by Mehdi-Panjwani** [hikalkan/jtable#1840]
![error jtable](https://cloud.githubusercontent.com/assets/8317870/10412798/31fca9e8-6fa2-11e5-8b72-67730a290936.png)
When I try to save tag <br> in a text field, I get error. Seems like jtable cannot save html angle bracket.
Any solution for this?

**Comment by hikalkan** [comment]
That does not seems related to jtable. If you're using ASP.NET MVC, it may block html inputs.

**Comment by Mehdi-Panjwani** [comment]
Thnx. It is related to jtable bcoz it is not even hitting asp.net mvc controller :(
I tried to debug using javascript alerts. Jtable stucks at _saveEditForm

**Comment by Mehdi-Panjwani** [comment]
you are absolutely right :)
MVC ASP.Net action was not allowing html content
I had to decorate the action with this tag [ValidateInput(false)]
