### ISSUE TITLE
want to select specific rows without reloading jtable

### ISSUE THREAD

**Issue by Siddhartha-Attri** [hikalkan/jtable#1852]
I want to select specific rows (say all rows with city column as 'delhi') of jtable without reloading the jtable.
Thanks in advance.

**Comment by hikalkan** [comment]
There are some methods you can combine to make it:

* Use $('#StudentTableContainer').find('.jtable-data-row') to get all rows, make a for loop to filter records with delhi.
* Use getRowByKey (http://jtable.org/ApiReference/Methods#met-getRowByKey) in for loop to get the record and check the delhi
* Use selectRows (http://jtable.org/ApiReference/Methods#met-selectRows) to select the rows.

**Comment by Siddhartha-Attri** [comment]
Thanks, it worked for me. However I did it the following way:-
$('#WagonTableContainerLeft').find('.jtable-data-row').each(function()																		                	  				{
if((($(this).data('record').consist)==field1)&& (field1!="") )																	                	  						{					                	  																							                	  						$(this).addClass('jtable-row-selected');
}
});
