### ISSUE TITLE
Load another jtable with selected row value

### ISSUE THREAD

**Issue by x-pkumar** [hikalkan/jtable#1856]
Hi,

I have 2 jTables, while selecting a row in 1st table, I need to pass selected row parameters to 2nd jtable action url and it loads 2nd Jtable. The 2nd jtable is located below the first jtable. can you suggest me how to do this..?

**Comment by erturkkadir** [comment]
Please check #1847

**Comment by x-pkumar** [comment]
Hi Kadir

Thanks for quick response. 

I'm getting error message saying that "Error: cannot call methods on jtable prior to initialization; attempted to call method 'load'"

see my code below

//1st Table:
 var seldata;
  	$(document).ready(function() {
		$('#FirstTableContainer').jtable({
			title : '',
			selecting: true,
			paging: true, //Enable paging
			pageSize: 10,
			sorting:true,
			defaultSorting: '',
			pageSizeChangeArea:true,
			columnSelectable:false, //hide selected columns
            toolbarsearch:true,
            actions: {
            	  listAction: '<%=resourceURL%>'+'&action=list',
            },
			fields : {
				Detail: {
                    title: 'Show',
                    width: '3%',
                    sorting: false,
                    edit: false,
                    create: false,
                    key:true,
                    pageSizeChangeArea:false,
        			columnSelectable:false,
        			animationsEnabled:false,
        			searchable:false,
                    display: function (studentData) {
                        //Create an image that will be used to open child table
                        var $img = $('<input type="radio" name="selectedAction" title="Click here"/>');
                        //Open child table when user clicks the image
                       // $img.click(function () {
                        //	var tabData = $('#MilestoneContainer').data();
                        	//alert(tabData.value);
                        	//call(studentData.record);
                        //});
                        //Return image to show on the person row
                        return $img;
                    }
                },
				
				_SHIPMENT_ID : {
					title : 'Shipment',
					sort :true,
					width : '12%',
					key : true,
					list : true,
					edit : false,
					create : false
				},
				_CONTAINER_ID : {
					title : 'Container #',
					sort :true,
					width : '12%',
					searchable:true,
					display: function (data) {
                        return data.record._CONTAINER_ID;
                    },
					edit : false
				}
				
			},selectionChanged: function () {
                //Get all selected rows
                var $selectedRows = $('#FirstTableContainer').jtable('selectedRows');
                $('#SelectedRowList').empty();
                if ($selectedRows.length > 0) {
                    $selectedRows.each(function () {
                        var selectedVal = $(this).data('record');
                        $('#MilestoneContainer').jtable('load', {seldata: selectedVal } );
                       
                    }); 
                } else {
                    //No rows selected
                    $('#SelectedRowList').append('No row selected! Select rows to see here...');
                }
            },
		});
		$('#FirstTableContainer').jtable('load');
	});



// 2nd jTable
$('#MilestoneContainer').jtable({
		seldata:{
        title: seldata._SHIPMENT_ID + ' - ' + ' Container: ' + seldata._CONTAINER_ID,
        columnSelectable:false,
        actions: {
            listAction: '<%=resourceURL%>'+'&action=details&rec='+seldata._SHIPMENT_ID,
        },
         fields: {
        	 ShipmentId: {
                 width: '20%',
                 type: 'hidden',
                 defaultValue: js_shipment
             },
        	 statusDate: {
                title: 'Date',
                width: '40%',
                sorting: false,
                edit: false,
                create: false,
                type: 'date',
                display: function (data) {
                    return moment(data.record.statusDate).format('MM/DD/YYYY HH:mm');
                }
            },
            type: {
                title: 'Milestone',
                edit: false,
                width: '40%'
            }
          }
		}
	    }).jtable('load');

// Divs
          <div
		style="width: 100%; margin-right: 0%; margin-left: 0%; text-align: center;">
		<div id="FirstTableContainer"></div>
	</div>
	<div><br/>All Status Messages<br/></div>
	<div
		style="width: 100%; margin-right: 0%; margin-left: 0%; text-align: center;">
		<div id="MilestoneContainer"></div>
	</div>

If i select any row in above table I'm trying to pass that object through "seldata". as per  your solution i modified by adding seldata but getting below error. any help will be appreciated.

**Comment by erturkkadir** [comment]
I did not execute the load method for child, since you need to call only whenever user clicks the button. I think removing the $('Milestonecontainer').load() method (line #109) may solve your problem.

**Comment by x-pkumar** [comment]
sorry, I didn't get you. My intention is when ever user clicks on radio button/selects a row, I need to show 2nd jtable with selected row values. But if i remove $('#MilestoneContainer').jtable('load', {seldata: selectedVal } ); statement how can i pass selected object to 2nd table..? how 2nd table will load/refresh for every selection..

please help me..thanks

**Comment by erturkkadir** [comment]
I assume there is a link between the master and detail table which is <b>container_id</b>, (if not please use your own). Here is the structure you have 
```javascript    
$('#ContainerTable').jtable(
     {title:'', ... },
     actions : {...},
     fields: {
        container_id: { // link between master and detail table
            title: 'Container_ID',
            key: true,
            edit: false,
            create: false
        }, ....	
    },
     selectionChanged: function() { // whenever user select a row
         var rows = $('#ContainerTable').jtable('selectedRows');
         container_id = rows.data('record').container_id;
         $('#MileStoneContainer').jtable('load', {container_id: container_id } );
     }
 });

$('#ContainerTable').jtable('load'); // Master Table 


// Now you need to create detail table instance (do not load)

$('#MileStoneContainer').jtable({
      title: '',
     actions: {...},
     fields: {  
	shipment_id: {  // Key for the detail table
          title: "#",
          list: false,
          edit: false,
          key: true,
        },
	container_id: {  // link to the master table
          title: 'Container_ID',
          list: false,
          edit: true,
         create: true,
         inputClass: 'validate[required]',
        options: 'php/l_accm.php'
      }
});

l_accm.php lists container_id with the container_name 

Please keep in mind that this is two separate div s. 

```
You would be able to see <b>container_no</b>, in the request for list at jTable calls. <br>

If you need more clarification I can post my full working code here to help you.

**Comment by x-pkumar** [comment]
Kadir,

Thank you for posting the snippet.

now I'm getting same error again: Uncaught Error: cannot call methods on jtable prior to initialization; attempted to call method 'load'

I modified my code as per your suggestions. but used shipment_id. 
Please review my attached code. 

[question.txt](https://github.com/hikalkan/jtable/files/42184/question.txt)

I need to pass selected  shipment_id value to MileStoneContainer action url also.

I'm struggling here from 4 days.

**Comment by x-pkumar** [comment]
Hey Kadir,

Any idea..?

**Comment by x-pkumar** [comment]
Yup,that would be great if you post your working code. So that i can debug mine. Thanks.

**Comment by erturkkadir** [comment]
Hi Kumar,

Sorry for delay, Here is the working code in my application 



```javascript

<div id='cust_m'><!-- customers table  --></div>
<div id='cust_d' ><!-- customer detail  table  --></div>


 $('#cust_m').jtable({
            title: '<?php echo $page; ?>',
            paging: true,
            sorting: true,
            selecting: true,
            defaultSorting: 'am_no ASC',
			openChildAsAccordion: true,
            actions: {
                listAction:   'php/xyz_m.php?action=list',
                createAction: 'php/xyz_m.php?action=create',
                updateAction: 'php/xyz_m.php?action=update',
                deleteAction: 'php/xyz_m.php?action=delete'
            },
            fields: {  
				am_no: {
					title: 'AccNo',
					key: true,
					edit: false,
					create: false,	
				},
				am_company: {
                    title: 'Company',
                    list: true,
					inputClass: 'validate[required]'
                },
				am_business: {
                    title: 'Business',
                    list: true,
					inputClass: 'validate[required]'
                },
                am_fname: {
                    title: 'F.Name',
                    list: true,
					inputClass: 'validate[required]'
                },
                am_lname: {
                    title: 'L.Name',
                    list: false,
					inputClass: 'validate[required]'
                },
                am_email: {
                    title: 'email',
                    list: true,
					inputClass: 'validate[required,custom[email]]'
                },
                am_phone1: {
                    title: 'Phone1',
                    list: true 
                },
				am_tdebit: {
					title: 'Debit',
					list: true,
					edit: false,
					create: false,
					listClass: 'align-right',
					display: function(data) {
						var c = parseFloat(data.record.am_tdebit);
						if(c>0)
							return formatDollar(c);
						else 
							return "";
					}
				},
				am_tcredit: {
					title: 'Credit',
					list: true,
					edit: false,
					create: false,
					listClass: 'align-right',
					display: function(data) {
						var c = parseFloat(data.record.am_tcredit)
						if(c>0)
							return formatDollar(c);
						else
							return "";
					}
				},
				am_forward: {
					title: 'Forward',
					list: true,
					edit: false,
					create: false,
					listClass: 'align-right',
					display: function(data) {
						var c = parseFloat(data.record.am_tdebit) - parseFloat(data.record.am_tcredit);
						if (c>0) 
							return "<a class='red'>"+formatDollar(c)+"</a>";
						else 
							return "";
					}
				},
                am_cost: {
                    title: 'cost',
                    list: false 
                },
                am_status: {
                    title: 'Status',
                    list: false,
					edit: true,
					options: { '1': 'Active', '0': 'Passive' },
                },
                am_remarks: {
                    type: 'textarea',
                    title: 'Remarks',
                    list: true 
                }
            },
			//Initialize validation logic when a form is created
            formCreated: function (event, data) {
                data.form.validationEngine();
            },
            //Validate form when it is being submitted
            formSubmitting: function (event, data) {
                return data.form.validationEngine('validate');
            },
            //Dispose validation logic when form is closed
            formClosed: function (event, data) {
                data.form.validationEngine('hide');
                data.form.validationEngine('detach');
            },
			selectionChanged: function(){
				var rows = $('#cust_m').jtable('selectedRows');
				am_no = rows.data('record').am_no;
				
				$('#cust_d').jtable('load', {am_no: am_no } );
			}
        });


            $('#cust_m').jtable('load');
            $('#cust_d').jtable({
				title: 'Activity',
				paging: true,
				sorting: true,
				actions: {
					listAction:   'php/xyz_d.php?action=list',
					createAction: 'php/xyz_d.php?action=create',
					updateAction: 'php/xyz_d.php?action=update',
					deleteAction: 'php/xyz_d.php?action=delete'
				},
				fields: {  
					cd_no: {
						title: "#",
						list: false,
						edit: false,
						key: true,
					},
					am_no: {
						title: 'Date',
						list: false,
						edit: true,
						create: true,
						inputClass: 'validate[required]',
						options: 'php/l_accm.php'
					},
					cd_date: {
						title: 'Date',
						list: true,
						inputClass: 'validate[required]'
					},
					cd_exp: {
						title: 'Explanation',
						list: true,
						inputClass: 'validate[required]'
					},
					cd_debit: {
						title: 'Debit',
						list: true,
						inputClass: 'validate[required]',
						listClass: 'align-right',
						display: function(data) {
							var c = parseFloat(data.record.cd_debit)
							if(c>0)
								return formatDollar(c);
							else
								return "";
						}
					},
					cd_credit: {
						title: 'Credit',
						list: true,
						inputClass: 'validate[required]',
						listClass: 'align-right',
						display: function(data) {
							var c = parseFloat(data.record.cd_credit)
							if(c>0)
								return formatDollar(c);
							else
								return "";
						}
					},
					inv_no: {
						title: 'Inv',
						list: true,
						display: function(data) {
							if(data.record.inv_no == 0) 
								return "";
							else
								return data.record.inv_no;
						}
					},
					upload: {
						title: 'Upload',
						type: 'file',
						create: false,
						edit: false,
						display: function(data) {
							return "<a href='#' class='button tiny icon-page blue-gradient' onclick='upload("+data.record.cd_no +")'>+</a>";
						}
					},
					show: {
						title: 'Show',
						list: true,
						create: false,
						edit: false,
						display: function(data) {
							var str = data.record.cd_path;
							if(str==null) return "";
							if(str=="") return "";
							return "<a href='"+data.record.cd_path+"' target='_blank' class='button tiny icon-zoom red-gradient'>View</a>";
						},
					},
				},
				formCreated: function (event, data) {
					data.form.validationEngine();
				},
				formSubmitting: function (event, data) {
					return data.form.validationEngine('validate');
				},
				formClosed: function (event, data) {
					data.form.validationEngine('hide');
					data.form.validationEngine('detach');
				}
			});	

and the php code for lookup

<?php
...
  $sql = "select am_no, am_company from xyz_m where 1 order by am_company";
  $db->query($sql);
  
  $jTableResult = array();
  $rows = array();
  while($row = $db->get_row()) {
	  $tmp = array();
	  $tmp['DisplayText'] = $row['am_company'];
	  $tmp['Value'] = $row['am_no'];
	  $rows[] = $tmp;
  }


  $jTableResult['Result'] = "OK";
  $jTableResult['Options'] = $rows;
  print json_encode($jTableResult);
    
  $db->closeDB();          
?>


Hope this code help you.
Kadir.

**Comment by x-pkumar** [comment]
Kadir,

Thank you, thank you very much for your code. I found the solution with the help of your code. Thanks dude.
