### ISSUE TITLE
No background on Add New Record popup

### ISSUE THREAD

**Issue by Harmonitron** [hikalkan/jtable#1858]
jTable version 2014-08-03.
Theme: Metro.

When I hit the Add New Record command the dialog pops up but the form background is transparent.
Can anyone give me a pointer on where to check?

Many thanks.

**Comment by Kostya5** [comment]
Check jquery-ui css theme

**Comment by Harmonitron** [comment]
Thanks Kostya5. HTML for the popup appears to be ...

    <div class="ui-dialog ui-widget ui-widget-content ui-corner-all ui-front ui-dialog-buttons ui-draggable ui-resizable"

for the first class in jquery-ui.css is ...

    .ui-dialog {
      background-color: white;	//<<-- my edit
      overflow: hidden;
      position: absolute;
      top: 0;
      left: 0;
      padding: .2em;
      outline: 0;
    }

Firebug is showing this when I select the div:

	element.style {
		display: block;
		height: auto;
		left: -51px;
		position: relative;
		top: -259.167px;
		width: auto;
	}
	body {
		font-family: "Trebuchet MS",sans-serif;
		font-size: 10pt;
	}

Any further ideas?

**Comment by JaredKnapp** [comment]
Include the 'jquery-ui-1.8.16.custom.css' to get it to work. From the 'Codes' directory in the zipped sample files:

/Codes/themes/redmond/jquery-ui-1.8.16.custom.css
/Codes/scripts/jtable/themes/metro/blue/jtable.min.css

**Comment by Harmonitron** [comment]
Delayed getting back to this.
I'm running 2.4.0 and I don't have .custom.css. Where should I find it and are you sure that it addresses my problem?
Thanks.

**Comment by Harmonitron** [comment]
OK. I solved it by including
  /jquery/jquery-us.css
as well as the ones in jtable.

Thanks.
