### ISSUE TITLE
Licence for using Jtable

### ISSUE THREAD

**Issue by abhishek13feb** [hikalkan/jtable#1882]
Do we need to purchase some license to use JTable in our applications

**Comment by hikalkan** [comment]
No, you can use or change it freely.

**Comment by abhishek13feb** [comment]
The website Jtable.Org is not available.Is there any known issues?

**Comment by hikalkan** [comment]
It's available: http://jtable.org/
Can you try again?

**Comment by abhishek13feb** [comment]
It is opening on my android phone but it is stuck on windows coMputer. It
was working fine two days back.It is stuck and keeps loading the site for
ever. I am using IE Edge.

**Comment by bencagri** [comment]
Why windows? Why IE Edge?

Double fail.
