### ISSUE TITLE
PHP Example VS jTable 2.4.0

### ISSUE THREAD

**Issue by gc9n** [hikalkan/jtable#1909]
i download the example  for PHP wich was working fine and it was running with jTable 2.0.0 so i downloaded the new version jTable 2.4.0 . 
After that i got white page in both php examples...
something that i miss?

**Comment by bencagri** [comment]
White page (mostly) occurs if error reporting disabled. Its not cause of jTable. Check your server conf. and open error reporting.

**Comment by gc9n** [comment]
Hi..
Unfortunetelly i have this option enabled and no error appear.. what i did also is to update 
jquery-ui-1.10.2/jquery-1.9.1.js
jquery-ui-1.10.2/ui/jquery-ui.js

but nothing..

**Comment by gc9n** [comment]
ok for the record , i download and istalled in php example , the folder script from MVC example and worked. just change the jquery version in php example!
