### ISSUE TITLE
Refresh Main Jtable 

### ISSUE THREAD

**Issue by gc9n** [hikalkan/jtable#1914]
Hello
is there any way to refresh Parent Jtable when Child Jtable closes?

**Comment by hikalkan** [comment]
You may use closeRequested event. See this code: https://github.com/hikalkan/jtable/blob/master/lib/jquery.jtable.js#L4888

So, you can add a closeRequested function in the second argument object of openChildTable. You can refresh main table here. But in this case, you should manually close the child table after your code.

**Comment by gc9n** [comment]
thanks a lot the response
basically wheN my user deletes every record in child jtable. The curent row in master jtable changes color. But tjis happens if I refresh manully.

**Comment by gc9n** [comment]
can somebody give an example,?
is there any way also Refreshing Master jtable on child jtable deletion of records?

**Comment by Kostya5** [comment]
Insert in child table:
`					recordDeleted: function (event, data) {
						$('#TableMain').jtable('reload');
					}
`

**Comment by gc9n** [comment]
Where in which place?

**Comment by gc9n** [comment]
don't work

'''Main table code
updateAction: 'new_index.php?action=update',
					
deleteAction: 'new_index.php?action=delete'
				},
				fields: {
				
					
			 		Payments: {
				   				pageSize: 30,
				sorting: true,

                    title: '',
                    width: '5%',
                   sorting: true,
                    edit: false,
                    create: false,
                    showCloseButton: true,
                     recordDeleted: function (event, data) { $('#PeopleTableContainer').jtable('reload'); }   
                ,    defaultSorting: 'imera DESC',
                    //formClosed: function () {$('#PeopleTableContainer').jtable('reload');},
                 
                    display: function (studentData) {
                    
                        //Create an image that will be used to open child table
                        var $img = $('<img src="list_metro.png" title="ΟΦΕΙΛΕΣ" />');
                        //Open child table when user clicks the image
                       
                        $img.click(function () {
                         
                                   
                            $('#PeopleTableContainer').jtable('openChildTable', 
                           
                            
                            $img.closest('tr'),
                            
                            
                            
                                    {
            						messages:grmsg,  //$sql="INSERT INTO services SET imerominia='$imerominia', service='$service', carid='$carId', xiliometra='$xiliometra'";
                                        title:'ΟΦΕΙΛΕΣ ' + studentData.record.odigos ,
                                        actions: {
                                       	    listAction:   'new_ofeiles_ids.php?action=list' + studentData.record.driverid,
											deleteAction: 'new_ofeiles_ids.php?action=delete' + studentData.record.id
											
                                        },
                                        fields: {
                                            driverid: {
                                                type: 'hidden',
                                                defaultValue: studentData.record.driverid
                                            },
                                            id: {
                                                key: true,
                                                create: false,
                                                edit: false,
                                                list: false
                                            },
                                            imera: {
                                                title: 'ΗΜΕΡΑ ΟΦΕΙΛΗΣ',
                                                width: '30%' ,
                                                  type: 'date',
					 							listClass:'bold',
                                                displayFormat: 'dd/mm/yy'
                                                
                                            }
                                       
                                        
                              
							    }
                                    }, function (data) {  
                                    
                                    data.childTable.jtable('load');
                                  //	if ( data.childTable.record == null)
                                  //  	{  
                                   //      	$('#PeopleTableContainer').jtable('load');
                                   // 	}
                                    //,	formClosed: function (event, data) {find('PeopleTableContainer').jtable('reload');   	}
                                    
                                    }
                                    );
                                    
                        }); 
                        //Return image to show on the person row
                        return $img;
                    }
                      
                    },

**Comment by gc9n** [comment]
This returns error

fields: {
				
					
			 		Payments: {
				   				pageSize: 30,
				sorting: true,

                    title: '',
                    width: '5%',
                   sorting: true,
                    edit: false,
                    create: false,
                    showCloseButton: true,
                    defaultSorting: 'imera DESC',
                    //formClosed: function () {$('#PeopleTableContainer').jtable('reload');},
                 
                    display: function (studentData) {
                    
                        //Create an image that will be used to open child table
                        var $img = $('<img src="list_metro.png" title="ΟΦΕΙΛΕΣ" />');
                        //Open child table when user clicks the image
                       
                        $img.click(function () {
                         
                                   
                            $('#PeopleTableContainer').jtable('openChildTable', 
                           
                            
                            $img.closest('tr'),
                            
                            
                            
                                    {
            						messages:grmsg,  //$sql="INSERT INTO services SET imerominia='$imerominia', service='$service', carid='$carId', xiliometra='$xiliometra'";
                                        title:'ΟΦΕΙΛΕΣ ' + studentData.record.odigos ,
                                        actions: {
                                       	    listAction:   'new_ofeiles_ids.php?action=list' + studentData.record.driverid,
											deleteAction: 'new_ofeiles_ids.php?action=delete' + studentData.record.id
											
                                        },
                                        fields: {
                                            driverid: {
                                                type: 'hidden',
                                                defaultValue: studentData.record.driverid
                                            },
                                            id: {
                                                key: true,
                                                create: false,
                                                edit: false,
                                                list: false
                                            },
                                            imera: {
                                                title: 'ΗΜΕΡΑ ΟΦΕΙΛΗΣ',
                                                width: '30%' ,
                                                  type: 'date',
					 							listClass:'bold',
                                                displayFormat: 'dd/mm/yy'
                                                
                                            }
                                       
                                        
                              
							    }
                                    }, function (data) {  
                                    
                                    data.childTable.jtable('load');
                                  //	if ( data.childTable.record == null)
                                  //  	{  
                                   //      	$('#PeopleTableContainer').jtable('load');
                                   // 	}
                                    //,	formClosed: function (event, data) {find('PeopleTableContainer').jtable('reload');   	}
                                    
                                    }
                                    ,
                                          recordDeleted: function (event, data) { $('#PeopleTableContainer').jtable('reload'); }   
               
                                    );
                                    
                        }); 
                        //Return image to show on the person row
                        return $img;
                    }

**Comment by Kostya5** [comment]
put here (in child table):

                                    title:'ΟΦΕΙΛΕΣ ' + studentData.record.odigos ,
                                    recordDeleted: function (event, data) { $('#PeopleTableContainer').jtable('reload'); }
                                    actions: {
                                        listAction:   'new_ofeiles_ids.php?action=list' + studentData.record.driverid,
                                        deleteAction: 'new_ofeiles_ids.php?action=delete' + studentData.record.id

                                    },

**Comment by gc9n** [comment]
Many thanks !! worked like a charm!
