### ISSUE TITLE
closeRequested ? where do i declare it ?

### ISSUE THREAD

**Issue by gc9n** [hikalkan/jtable#1919]
Help guys 
where do i declare closeRequested ? in child form , in parent form?

2 days i am strugling for this to work , 
this closeRequested ignores me entirerly.  what i want is Refresh main when i close Child! that simple.!!
what the hell is happening. i got the latest jtable vesrion
```

$('#PeopleTableContainer').jtable({
			 messages:grmsg,
				title: 'calendari',
			 	defaultSorting: 'pinakida ASC',
				paging: true,
				pageSize: 50,
				sorting: true,
				openChildAsAccordion: true,
		                closeRequested: function (event, data) {
           	    			    alert('Hello World');
                                            $('#PeopleTableContainer').jtable('reload');
                                    },
	 
				actions: {
					listAction:   'new_index.php?action=list',
					createAction: 'new_index.php?action=create',
					updateAction: 'new_index.php?action=update',
					deleteAction: 'new_index.php?action=delete'
				},
				fields: {
				
					
			 		Payments: {
```

**Comment by hikalkan** [comment]
You should add it to the child table, not parent table. Because, you are closing the child table.

**Comment by gc9n** [comment]
I did add it there obsiously , but it doesn't work ,where sould I add it after or before fields declaration of child 
, please help
