### ISSUE TITLE
Custom display not triggering modal (.click)

### ISSUE THREAD

**Issue by GManNAtl** [hikalkan/jtable#1950]
I have this custom display to create my own edit button.

`display: function(data) {
     return '<a href="#" data-href="menu_pricing.php?recordID=' + data.record.recordID + '" class="priceButton"><span class="mif-pencil icon"></span></a>';
                }`

I have a jQuery click action bound to the class priceButton that triggers the modal. If I copy this code out to a test link outside of jTable it works perfectly fine and triggers the modal. For some reason inside jTable it is not even triggering the "click" at all from debugging in developer tools.

I have tried using preventDefault in the called function. I have also tried making this a button as opposed to a link. I have also tried using "inline javascript (ie onclick) as opposed the using a jQuery selector. No matter what I do it behaves as if you had done nothing.

I am using the MetroUI CSS framework for this particular project although I doubt this matters too much. Didn't know if someone has ran into a similar problem with another framework. BTW, I use this exact display function on other jTables and it works fine as long as you are going to a straight link in the href vs. the data-href/modal process.

**Comment by hikalkan** [comment]
You should use jQuery's "on" while registering to the events for dynamically added elements. See it's documentation.

Alternatively, you can register to click event of new added element before returning it in the display function.

**Comment by GManNAtl** [comment]
Perfect! Thanks for the help on this.This lesson will definitely stick with me and is certain to help in the future with similar problems.

**Comment by hikalkan** [comment]
You're welcome :)
