### ISSUE TITLE
Functionas as actions

### ISSUE THREAD

**Issue by loonighan** [hikalkan/jtable#1969]
First of all thanks for jTable, thanks for keeping it open.
In earlier versions, before actions could be functions, additional post data could only be passed modifying the url string. To do that I modified the source so that list/create/update/delete Actions url could be modified after instantiation. Sorry, I had no choice.
Now with functions as actions the post  data solves the issue, however it's not clear where jtParams and postData variables to the deferred function are declared and waht their scope is.
Furthermore jtStartIndex, jtPageSize and jtSorting can be retrieved from $_REQUEST in php but postData is not present.

**Comment by hikalkan** [comment]
Have you seen the document: http://jtable.org/ApiReference/Actions#act-listAction

````js
listAction: function (postData, jtParams) {
    return $.Deferred(function ($dfd) {
        $.ajax({
            url: '/Demo/StudentList?jtStartIndex=' + jtParams.jtStartIndex + '&jtPageSize=' + jtParams.jtPageSize + '&jtSorting=' + jtParams.jtSorting,
            type: 'POST',
            dataType: 'json',
            data: postData,
            success: function (data) {
                $dfd.resolve(data);
            },
            error: function () {
                $dfd.reject();
            }
        });
    });
}
````

postData is passed as the first argument to listAction.

**Comment by loonighan** [comment]
Tahnk you for your reply.
I ve seen the documentation and I have debugged jtable with chrome console extensively trying to work out the scope of the variables.
These variables as far as I can seen are not declared in jtable.js. **So I've declared them in my javascript** as:
var postData = {id:1};
var jtParams = {jtStartIjdex:0,jtPageSize:15,jtSorting:'id ASC'};

The load() method processes the initial values of jtParams, but if a column is clicked the jtSorting is not changed and there is no event to indicate that a column has been clicked and that jtParams.jtSorting should be changed.

It is as if the declared jtParams is passed to jtable.js by value rather than by reference, if the term applies here.

Also I've looked into the demo page source for the variables but there's no trace of them.

Any comments would be appreciated.

**Comment by hikalkan** [comment]
Hi,

If a column is clicked, then the loadAction is called again with new parameters. So, you shouldn't store it as a global variable normally.

**Comment by loonighan** [comment]
Ok, working now. 

postData and jtParams are passed to the deferred ajax function.
jtParams is update by jTable on paging and sorting events.
postData comes from the initial or subsequent load method calls.

Early morning seems better than late at night for understanding the documentation.
Thanks
