### ISSUE TITLE
Angularjs Table

### ISSUE THREAD

**Issue by vijayphani** [hikalkan/jtable#1975]
Its high time, we need a Angularjs Table. As of now ng-Grig and an-Grid and Kendo Grid are all useless when compared to jTable. Ibrahim Kalkan do you have any plans of converting this grid to angular js.

**Comment by hikalkan** [comment]
I use ui-grid (http://ui-grid.info/) for angular. It is well integrated to angularjs and maintained by Google. So, I don't think to create an angularjs version of jTable.

**Comment by vijayphani** [comment]
Tried ui-grid and it does not even have quarter of the feature set of your jTable.  Most sorting and paging is on the client side and it is really in efficient. I know I am asking too much, but if someone is willing to fork your code and write it in angularjs, I am willing to contribute.

**Comment by hikalkan** [comment]
Hi,

ui-grid has server side paging and sorting. I also don't like it's option structure much but has many features.

**Comment by pmapkiranch** [comment]
Hi 
I've started angular version of jtable please refer
https://github.com/pmapkiranch/angular-jtable
