### ISSUE TITLE
how to handle multi line text?

### ISSUE THREAD

**Issue by chrislouvion** [hikalkan/jtable#1980]
One of my table field is text stored with line breaks; when rendered and edited, line breaks are removed. Is there an option or work around to keep multi line text rendered and edited as defined?

**Comment by chrislouvion** [comment]
ok, solved it myself; simply use a <textarea> in the display function.

**Comment by faceyy** [comment]
Hi,

is it possible for you to post a code example of your soultion?

Greetings

**Comment by chrislouvion** [comment]
fields: {
message: {
                    title: 'Image Text',
                    width: '76%',
                    display: function (data) {
                        return '<textarea cols="100" rows="20">' + data.record.message + '</textarea>';
                    },
                    input: function (data) {
                        return '<textarea name="message" cols="140" rows="18">' + data.record.message + '</textarea>';
                    }
                },
}
