### ISSUE TITLE
Set Modal width size for Create and Edit Modal

### ISSUE THREAD

**Issue by AdithonLee** [hikalkan/jtable#1989]
!!!Please help me!!!.When I click on Add new record or Edit the modal box width size not cover the data as in picture.

Thank you.
![modalbox-width issue](https://cloud.githubusercontent.com/assets/22464462/18860091/23c03fee-84a4-11e6-9743-833d25942301.png)

**Comment by hikalkan** [comment]
Just use some css. Optionally, you can write a handler for formCreated event (http://jtable.org/ApiReference/Events#event-formCreated) to change modal's size via jQuery.

**Comment by AdithonLee** [comment]
It's work, Thank you very much hikalkan.
