### ISSUE TITLE
Child versus master update/create

### ISSUE THREAD

**Issue by amberdiehl** [hikalkan/jtable#1994]
Hi!

I have a:

Parent
----- Child
----------- Child

nested data structure. Seems to be loading data okay but I am not seeing the same lovely UI interaction with the child tables as occur in the parent.

E.g. On successful creation of a record for the parent and returning the key, and data, the create dialog box is closed and the record is added to the table. 

With the first level child this is not happening. The create dialog box remains open and I have to manually refresh the page and click through to the child table to see that record has been added.

I am wondering if that is expected behavior or there is something wrong with my setup/environment?

The record is being added and with debug I have confirmed the right info is being sent back.

Thanks in advance for your help. This jTable is amazing.

PS. More info: I completed the update and delete functions and they DO update the child jTable object dynamically, same as the parent. I thought it might be an issue with the child that's nested inside (the first child), so I made sure the 'list' action operates (just in case), but that didn't matter. So, what do you think could be causing this with the create action?

**Comment by Gonlos** [comment]
Can you make screenshot from the right info that is being sent back?

**Comment by amberdiehl** [comment]
Absolutely! See attached!
<img width="867" alt="screen shot 2016-10-07 at 6 48 14 pm" src="https://cloud.githubusercontent.com/assets/5828080/19209416/c0a6fed4-8cbe-11e6-99f6-ecc8fe3bd93b.png">

**Comment by amberdiehl** [comment]
Never mind--I now have a new error, but I need to debug that first. I see that I was returning 'Records' not 'Record' and that was causing the error. Thank you so much for replying and helping me. 

As an aside, I have since implemented custom fields and implemented my own field validation. jTable really is amazing. Thank you all for your work and support.
