### ISSUE TITLE
Jtable Not showing Server error message on UI

### ISSUE THREAD

**Issue by mishrav98** [hikalkan/jtable#2019]
Hi,
I have integrated Jtable with JSP+Servlet. it is working fine in success scenario but whenever some error occurs in server, jtable always shows error dialog with message "An error occured while communicating to the server." although i'm passing server error message in below format but still it doesn't show the server error on UI
Json string passed from server : {'Result'="ERROR",'Message'="ORA-00001: unique constraint (MTUSER.UN) violated"}
request you to please help me in this issue as i have a demo planned for this and it's kind of urgent.

Thanks,
Vivek

**Comment by mishrav98** [comment]
Guys anyone who can help me here ?

**Comment by mishrav98** [comment]
@hikalkan.. can you please help me here. i really need this..

**Comment by mishrav98** [comment]
@hikalkan   can you please help sir ?

**Comment by hikalkan** [comment]
Hi,

````
{'Result'="ERROR",'Message'="ORA-00001: unique constraint (MTUSER.UN) violated"}
````

is not a valid JSON value. In JSON, you should use ``:``, not ``=``. Also, use double quotei instead of single. It should be like that:

````
{"Result":"ERROR","Message":"ORA-00001: unique constraint (MTUSER.UN) violated"}
````

**Comment by mishrav98** [comment]
@hikalkan  Hello Sir....thanks for your reply but i tried below format as well but it is not working and i'm still seeing generic error message on UI 
 {"Result":"ERROR","Message":"ORA-00001: unique constraint (MTUSER.UN) violated"}
Generic Error message everytime i'm getting as below 
"An error occured while communicating to the server." 


Request you to please check this and help me here.

Thanks

**Comment by mishrav98** [comment]
@hikalkan   Sir it worked after i removed the whitespace in my server error message. thanks for you time and reply.


Thanks,
