### ISSUE TITLE
change border color of child table

### ISSUE THREAD

**Issue by dasguptahirak** [hikalkan/jtable#2026]
Is it possible to change border color of child table?

Because the last row of child table and the next row of parent table are not distinguishable.
Please have a look on the screenshot below:
![image](https://cloud.githubusercontent.com/assets/7932509/22412886/e8fdd280-e6d8-11e6-94bf-0b05c092cb18.png)

**Comment by hikalkan** [comment]
Sure, just some css:

````
.jtable-child-table-container{
  border:2px solid red;
}
````

**Comment by dasguptahirak** [comment]
@hikalkan sir: You made my day.
I have just shown your reply to my office colleagues, they are equally happy and inspired.

**Comment by Siddhartha-Attri** [comment]
Thanks, but is there any way to change the theme of child table.
