### ISSUE TITLE
[Ask] - Looping some field jTable

### ISSUE THREAD

**Issue by harizal** [hikalkan/jtable#2029]
hi @hikalkan 

for this version of jtable, can we show List or array on field ?
i mean, i have object like this :

`public class Category{`
`      public int Id {get; set;}`
`      public string Name {get; set;}`
`}`
`public class Music`
`{`
`      public int Id {get; set;}`
`      public string Title {get; set;}`
`      public List<Category> {get; set;}`
`}`

i want to show Music on JTable like this :

<table>
<tr>
<td>ID</td>
<td>Title</td>
<td>Categories</td>
</tr>
<tr>
<td>1</td>
<td>Title 1</td>
<td>Categori1,Categori2</td>
</tr>
<tr>
<td>2</td>
<td>Title 2</td>
<td>Categori1,Categori2,Categori3, Categori4</td>
</tr>
</table>
can we do that on last vesion of Jtable ??
thanks

**Comment by hikalkan** [comment]
you can use display option to customize column rendering: http://jtable.org/ApiReference/FieldOptions#fopt-display
In this method, you can create a string by joining items in data.record.Categories

**Comment by harizal** [comment]
thank @hikalkan
