### ISSUE TITLE
Upload file click event not triggered from the jtable

### ISSUE THREAD

**Issue by MaheswariSubburathinam** [hikalkan/jtable#2039]
I have the requirement of upload file from the list view. I have list of items, first two columns are master child table, 3rd column is a image control which will be the event raiser for file upload click event. Inside the image click event i triggered the file uploader click event but it is not firing. Can you please help me to sort out the problem. Urgent!!!

 display: function (quoteHeaderData) {
                    //Create an image that will be used to open child table
                    var $img1;
                    
                    if (quoteHeaderData.record.DocID > 0)
                        $img1 = $('<img class="child-opener-image" src="/images/QuoteDetailCustomer.png" title="Edit Quote Trans" />');
                    else
                        $img1 = $('<img class="child-opener-image" src="/images/QuoteDetailProduct.png" title="Edit Quote Trans" />');
                    //Open child table when user clicks the image
                    $img1.click(function (e) {
                        $("#hndFileQuoteHeader").val(quoteHeaderData.record.QuoteHeaderID);
                        **$("#fileQuoteHeader").click();**
                    });
                    //Return image to show on the person row
                    return $img1;
                }

**Comment by saravanakumarv** [comment]
can you please show your user interface.then i can give my suggestions.so if you can

**Comment by MaheswariSubburathinam** [comment]
Hi,


I have attached the screenshot for user interface.


Thanks,

Maheswari S.


________________________________

**Comment by saravanakumarv** [comment]
where u have attached the screen shots.i did not see any attachments here.pls upload as a image then only others can help you.i hope you understand.because visualizing helps more imporvements.so pls attach your screenshots.

thank you

**Comment by MaheswariSubburathinam** [comment]
Sorry, I send it thru mail. I have placed now
![fileuploaderimage](https://cloud.githubusercontent.com/assets/20282269/24494355/9bb528ac-154f-11e7-8399-62177f61b52f.png)

**Comment by saravanakumarv** [comment]
by clicking that (p) img or icon u need to open a file control button(html control) as a child table and the uploaded file will be stored into database???

this is your need i think so

i will post my code once i finish it.

thank you

**Comment by MaheswariSubburathinam** [comment]
Yes. absolutely.. Thanks..

**Comment by saravanakumarv** [comment]
only file name only  going to save in database.file will be stored into your local directory.u need to create some folders to store

**Comment by MaheswariSubburathinam** [comment]
Yes. You are right.. I wanted the file control needs to be get the file from the end user when the image has clicked.. And send the source of image to controller as a Ajax call. If so I will take care of storage and getting the files. And also one more help, Is that possible to if there is a image on Mouseover it suppose to display as a tooltip.

**Comment by saravanakumarv** [comment]
nothing is impossible

**Comment by saravanakumarv** [comment]
you can do it on mouse over event by js.

**Comment by saravanakumarv** [comment]
https://github.com/hikalkan/jtable/issues/1252


try  this and post ur comments. first try file upload function alone.if it is working you can join with parent table

thank you

**Comment by saravanakumarv** [comment]
https://github.com/hikalkan/jtable/issues/323 Try this too

**Comment by MaheswariSubburathinam** [comment]
Thank you for your quick response.
My requirement is different. I don't want it to be on CREATE OR EDIT. I wanted this on LIST page only. From the list page itself when clicking the image I wanted to be upload the image to the database. Please sort out.

**Comment by MaheswariSubburathinam** [comment]
One more thing I don't want the file up-loader control visible. It should be visible false. When image has clicked the file control click events needs to be triggered..

**Comment by saravanakumarv** [comment]
i will give my code once i complete.i will show file upload control by child table.once the image or icon of the parent table is clicked the child table will be open.then you can upload your files.


is it correct??

**Comment by saravanakumarv** [comment]
or you wont need any child tables???

**Comment by MaheswariSubburathinam** [comment]
No. I coded for child tables, it is working fine. I wanted the image file uploader in parent table LIST view only.

**Comment by saravanakumarv** [comment]
oh that image will act like file upload control??

**Comment by saravanakumarv** [comment]
so you dont like to display BROWSE button on the list,for that u need that function in image. is it correct

**Comment by saravanakumarv** [comment]
fields: {
           ,
            Attach: {
               input : function (data){
                return "<input type='file' ...  >"; // OR----->
                return "<asp:FileUpload ....    >" ;// or----->   
               }
          }

try this

**Comment by MaheswariSubburathinam** [comment]
Yes..

**Comment by saravanakumarv** [comment]
https://github.com/hikalkan/jtable/issues/1290
try this too.

**Comment by saravanakumarv** [comment]
fields: {
                FileName: {
                    title: "Document"
                },
                docBytes: {
                    title: "Document Upload",
                    list: false,
                    create: true,
                    input: function (data) {
                        return '<input id="docBytes" type="file" name="docBytes" /><iframe name="postiframe" id="postiframe" style="display: none" />';
                    }
                }

**Comment by saravanakumarv** [comment]
and one more thing they released jtable latest version.try that one also.there you can see any file upload process

**Comment by saravanakumarv** [comment]
http://www.vhghorecha.in/jtable-jquery-plugin-file-upload-control/

**Comment by saravanakumarv** [comment]
http://stackoverflow.com/questions/39024603/jtable-uploading-an-input-file

**Comment by saravanakumarv** [comment]
now you can do

**Comment by MaheswariSubburathinam** [comment]
Sorry to trouble you. None of the samples are help me out in this issue.
Please can you give other solutions.. If you want I can share my piece of code also.

**Comment by saravanakumarv** [comment]
share your codes.then i can make better solution.i will also try once i get free

**Comment by MaheswariSubburathinam** [comment]
QuoteDocUpload - is the field item I am trying to work on..

function QuoteHeaderTableBinding() {
    $('#divSupplierQuoteInfo').jtable({
        title: 'Supplier Quotation List',
        paging: true,
        pageSize: 10,
        sorting: true,
        defaultSorting: 'Name ASC',
        recordAdded: function (event, data) {
            $('#divSupplierQuoteInfo').jtable('reload');
        },
        recordUpdated: function (event, data) {
            $('#divSupplierQuoteInfo').jtable('reload');
        },
        actions: {
            listAction: '/Admin/QuoteHeaderList?SupOrgID=' + $('#ddlSupplierQuotationOrgList').val() + '&QStatusID=' + $('#ddlSupplierQuotationStatus').val(),
            deleteAction: '/Admin/DeleteQuoteHeader',
            updateAction: '/Admin/UpdateQuoteHeader',
            createAction: '/Admin/CreateQuoteHeader'
        },
        fields: {
            QuoteHeaderID: {
                key: true,
                create: false,
                edit: false,
                list: false
            },
            QuoteDetails: {
                title: '',
                width: '5%',
                sorting: false,
                edit: false,
                create: false,
                listClass: 'child-opener-image-column',
                recordAdded: function (event, data) {
                    $('.jtable-child-table-container').jtable('reload');
                },
                display: function (quoteHeaderData) {
                    //Create an image that will be used to open child table
                    var $img = $('<img class="child-opener-image" src="/images/QuoteDetailProduct.png" title="Edit Quote Details" />');
                    //var $img = $('<i class="fa fa-product-hunt child-opener-image" aria-hidden="true" title="Edit Quote Details"></i>');
                    //Open child table when user clicks the image
                    $img.click(function () {
                        $('#divSupplierQuoteInfo').jtable('openChildTable',
                                $img.closest('tr'),
                                {
                                    title: 'Products Serviced',
                                    showCloseButton: true,
                                    actions: {
                                        listAction: '/Admin/QuoteDetailList?QuoteHeaderID=' + quoteHeaderData.record.QuoteHeaderID,
                                        updateAction: '/Admin/UpdateQuoteDetail',
                                        createAction: '/Admin/CreateQuoteDetail'
                                    },
                                    fields: {
                                        QuoteHeaderID: {
                                            type: 'hidden',
                                            defaultValue: quoteHeaderData.record.QuoteHeaderID
                                        },
                                        QuoteDetailID: {
                                            key: true,
                                            create: false,
                                            edit: false,
                                            list: false
                                        },
                                        OrgProductTypeID: {
                                            title: 'Product TypeID',
                                            list: false,
                                            create: true,
                                            edit: true,
                                            options: '/Admin/GetOrgProductType'
                                        },
                                        OrgProductTypeServiceID: {
                                            title: 'Product Type ServiceID',
                                            create: true,
                                            edit: true,
                                            list: false,
                                            dependsOn: 'OrgProductTypeID',
                                            options: function (data) {
                                                if (data.dependedValues.OrgProductTypeID != '') {
                                                    return '/Admin/GetOrgProductTypeService?OrgProductTypeID=' + data.dependedValues.OrgProductTypeID;
                                                } else {
                                                    return [{ DisplayText: 'Select type to see product type service', Value: 0 }]
                                                }
                                            }
                                        },
                                        ProductID: {
                                            title: 'Products',
                                            create: true,
                                            edit: true,
                                            list: false,
                                            dependsOn: 'OrgProductTypeID',
                                            options: function (data) {
                                                if (data.dependedValues.OrgProductTypeID != '') {
                                                    return '/Admin/GetProducts?prdtype=' + data.dependedValues.OrgProductTypeID;
                                                } else {
                                                    return [{ DisplayText: 'Select type to see products', Value: 0 }]
                                                }
                                            }
                                        },
                                        ProductName: {
                                            title: 'Product Name',
                                            create: false,
                                            edit: false,
                                            list: true,
                                        },
                                        SchedID: {
                                            title: 'Schedules',
                                            create: true,
                                            edit: true,
                                            list: false,
                                            dependsOn: 'ProductID',
                                            options: function (data) {
                                                if (data.dependedValues.ProductID != '') {
                                                    return '/Admin/GetSchedules?prdd=' + data.dependedValues.ProductID;
                                                } else {
                                                    return [{ DisplayText: 'Select product to see schedules', Value: 0 }]
                                                }
                                            }
                                        },
                                        StartDateTime: {
                                            title: 'Sched Date Time',
                                            width: '15%',
                                            list: true,
                                            create: false,
                                            edit: false
                                        },
                                        Naration: {
                                            title: 'Naration',
                                            type: 'textarea',
                                            list: true
                                        },
                                        Qty: {
                                            title: 'Qty',
                                            list: true
                                        },
                                        PricePerQty: {
                                            title: 'Price Per Qty',
                                            list: true
                                        }
                                    }
                                }, function (data) { //opened handler
                                    data.childTable.jtable('load');
                                });
                    });
                    //Return image to show on the person row
                    return $img;
                }
            },
            QuoteTrans: {
                title: '',
                width: '5%',
                sorting: false,
                edit: false,
                create: false,
                listClass: 'child-opener-image-column',
                recordAdded: function (event, data) {
                    $('.jtable-child-table-container').jtable('reload');
                },
                display: function (quoteHeaderData) {
                    //Create an image that will be used to open child table
                    var $img = $('<img class="child-opener-image" src="/images/QuoteDetailCustomer.png" title="Edit Quote Trans" />');
                    //Open child table when user clicks the image
                    $img.click(function () {
                        $('#divSupplierQuoteInfo').jtable('openChildTable',
                                $img.closest('tr'),
                                {
                                    title: 'Sold for Customers',
                                    showCloseButton: true,
                                    actions: {
                                        listAction: '/Admin/QuoteTransList?QuoteHeaderID=' + quoteHeaderData.record.QuoteHeaderID,
                                        updateAction: '/Admin/UpdateQuoteTran',
                                        createAction: '/Admin/CreateQuoteTran'
                                    },
                                    fields: {
                                        QuoteHeaderID: {
                                            type: 'hidden',
                                            defaultValue: quoteHeaderData.record.QuoteHeaderID
                                        },
                                        QuoteTranID: {
                                            key: true,
                                            create: false,
                                            edit: false,
                                            list: false
                                        },
                                        OrgProductTypeID: {
                                            title: 'Product TypeID',
                                            list: false,
                                            create: true,
                                            edit: true,
                                            options: '/Admin/GetOrgProductType'
                                        },
                                        ProductID: {
                                            title: 'Products',
                                            create: true,
                                            edit: true,
                                            list: false,
                                            dependsOn: 'OrgProductTypeID',
                                            options: function (data) {
                                                if (data.dependedValues.OrgProductTypeID != '') {
                                                    return '/Admin/GetProducts?prdtype=' + data.dependedValues.OrgProductTypeID;
                                                } else {
                                                    return [{ DisplayText: 'Select type to see products', Value: 0 }]
                                                }
                                            }
                                        },
                                        SchedID: {
                                            title: 'Schedules',
                                            create: true,
                                            edit: true,
                                            list: false,
                                            dependsOn: 'ProductID',
                                            options: function (data) {
                                                if (data.dependedValues.ProductID != '') {
                                                    return '/Admin/GetSchedules?prdd=' + data.dependedValues.ProductID;
                                                } else {
                                                    return [{ DisplayText: 'Select product to see schedules', Value: 0 }]
                                                }
                                            }
                                        },
                                        TranID: {
                                            title: 'Booking Reference No.',
                                            create: true,
                                            edit: true,
                                            list: false,
                                            dependsOn: 'ProductID,SchedID',
                                            options: function (data) {
                                                if (data.dependedValues.ProductID != '' && data.dependedValues.SchedID != '') {
                                                    return '/Admin/GetTranCustomerList?prdd=' + data.dependedValues.ProductID + '&schdd=' + data.dependedValues.SchedID;
                                                } else {
                                                    return [{ DisplayText: 'Select product/schedule to see customers', Value: 0 }]
                                                }
                                            }
                                        },
                                        BookingReferenceID: {
                                            title: 'Booking Reference No.',
                                            list: true,
                                            create: false,
                                            edit: false,
                                        },
                                        CustomerName: {
                                            title: 'Customer Name',
                                            list: true,
                                            create: false,
                                            edit: false
                                        }
                                    }
                                }, function (data) { //opened handler
                                    data.childTable.jtable('load');
                                });
                    });
                    //Return image to show on the person row
                    return $img;
                }
            },
            QuoteDocUpload: {
                title: '',
                width: '5%',
                sorting: false,
                edit: false,
                create: false,
                listClass: 'child-opener-image-column',
                //display: function (quoteHeaderData) {
                //    //Create an image that will be used to open child table
                //    var $img1;
                    
                //    if (quoteHeaderData.record.DocID > 0)
                //        $img1 = $('<img class="child-opener-image" src="/images/QuoteDetailCustomer.png" title="Edit Quote Trans" />');
                //    else
                //        $img1 = $('<img class="child-opener-image" src="/images/QuoteDetailProduct.png" title="Edit Quote Trans" />');
                //    //Open child table when user clicks the image
                //    $img1.click(function (e) {
                //        $("#hndFileQuoteHeader").val(quoteHeaderData.record.QuoteHeaderID);
                //        $("#fileQuoteHeader").click();
                //    });
                //    //Return image to show on the person row
                //    return $img1;
                //},
                input: function (data) {
                    return '<input type="file" name="moh">';
                }
            },
            BuyerOrgName: {
                title: 'Buyer Org Name',
                width: '12%',
                list: false,
                create: false,
                edit: false
            },
            BuyerOrgContactPerson: {
                title: 'Our Contact',
                width: '12%',
                list: true,
                create: false,
                edit: false
            },
            BuyerPersonID: {
                title: 'Buyer Person ID',
                list: false,
                create: true,
                edit: true,
                options: '/Admin/GetContactByRoleID?intOrgID=0&intRoleID=14' //14 - Org Contact
            },
            SupplierOrgContactPerson: {
                title: 'Supplier Contact',
                width: '12%',
                list: true,
                create: false,
                edit: false
            },
            SupplierOrgID: {
                title: 'Supplier Org ID',
                type: 'hidden',
                create: true,
                list: false,
                edit: false,
                defaultValue: $("#ddlSupplierQuotationOrgList").val()
            },
            SupplierContactPersID: {
                title: 'Supplier Contact Person ID',
                list: false,
                create: true,
                edit: true,
                options: '/Admin/GetContactByRoleID?intOrgID=' + $("#ddlSupplierQuotationOrgList").val() + '&intRoleID=14' //14 - Org Contact
            },
            QuoteNumber: {
                title: 'Quote Number',
                //width: '12%',
                list: true,
                create: true,
                edit: true
            },
            QuoteReference: {
                title: 'Quote Reference',
                width: '14%',
                list: true,
                create: true,
                edit: true
            },
            QuoteDate: {
                title: 'Quote Date',
                width: '15%',
                type: 'date',
                displayFormat: 'dd.mm.yy',
                list: false,
                create: true,
                edit: true
            },
            QuoteTotalAmount: {
                title: 'Quote Total Amount',
                width: '14%',
                list: true,
                create: true,
                edit: true
            },
            QuoteStatusTypeID: {
                title: 'Quote Status TypeID',
                list: false,
                create: true,
                edit: true,
                options: '/Admin/GetQuoteStatusTypes'
            },
            ServiceForClientOrgID: {
                title: 'Corporate Client ID',
                list: false,
                create: true,
                edit: true,
                options: '/Admin/GetClientQuoteOrgList?intOrgTypeID=' + $("#ddlSupplierQuotationType").val()
            }
        }
    });
    //Load student list from server
    $('#divSupplierQuoteInfo').jtable('load');
}

**Comment by saravanakumarv** [comment]
i will give my code soon.thank you

**Comment by MaheswariSubburathinam** [comment]
Finally I got a workaround for this issue. 
Step 1 - In display I directly placed the file upload control instead of image. Now the click event of file control triggered.
Step 2 - Implemented the "http://markusslima.github.io/bootstrap-filestyle/" for file control to change the GUI as expected.

**Code Sample-**
QuoteDocUpload: {
                title: '',
                width: '5%',
                sorting: false,
                edit: false,
                create: false,
                listClass: 'child-opener-image-column',
                display: function (quoteHeaderData) {
                    //Create an image that will be used to open child table
                    var $img1 = $('<input type="file" name="FileSelect" width="40px">');

                    $img1.change(function (e) {
                        $("#hndFileQuoteHeader").val(quoteHeaderData.record.QuoteHeaderID);
                        QuoteDocUpload(this);
                    });
                    //Return image to show on the person row
                    return $img1;
                }
            },

**FileStyle Implementation**

$(document).ajaxStop(function () {
    $('input[name=FileSelect]').filestyle({ input: false, buttonText: "" });
});

**Output of Image - Now the screen looks like this. This is somewhat OK even it is not a best one.**

![fileuploaderimage1](https://cloud.githubusercontent.com/assets/20282269/24537482/fff21f0e-15ff-11e7-85db-b159156ce0fd.png)
