### ISSUE TITLE
Url issue

### ISSUE THREAD

**Issue by asanad** [hikalkan/jtable#2043]
i create open action and when i click this action it throw exception 
**The length of the URL for this request exceeds the configured maxUrlLength value.**
http://localhost:6234/Mpa/MyInbox/0=h&1=t&2=t&3=p&4=%3A&5=%2F&6=%2F&7=l&8=o&9=c&10=a&11=l&12=h&13=o&14=s&15=t&16=%3A&17=6&18=2&19=3&20=4&21=%2F&22=M&23=p&24=a&25=%2F&26=E&27=v&28=e&29=n&30=t&31=%2F&32=D&33=e&34=t&35=a&36=i&37=l&38=%3F&39=S&40=N&41=%3D&42=1&43=4&44=_&45=6&46=0&47=%26&48=R&49=e&50=q&51=u&52=e&53=s&54=t&55=I&56=d&57=%3D&58=2

my code as the following 

          actions: {
                    title: app.localize('Actions'),
                    width: '5%',
                    sorting: false,
                    list: _permissions.open ,
                    display: function (data) {
                        var $span = $('<span></span>');

                        if (_permissions.open) {
                            $("<a href=\'" + **$.param(data.record.wfData)** + "'\ class=\'action-icon font-blue'\" title=\'" + app.localize('OpenTask') + "'\"><i class='fa fa-file-text-o font-blue font-lg' ></i></a>")
                                .appendTo($span);
                            console.log(data.record.wfData);                     
                        }
                                       
                        return $span;
                    }
                },

**console.log(data.record.wfData) >> http://localhost:6234/Mpa/Event/Detail?SN=14_60&RequestId=2**

Any idea why url changed ?

**Comment by hikalkan** [comment]
It maybe because of $.param. Write this to console:

``$.param('http://localhost:6234/Mpa/Event/Detail?SN=14_60&RequestId=2');``

You will see the result.
