### ISSUE TITLE
You can provide a jtable of the bootstrap style

### ISSUE THREAD

**Issue by ShiWei-L** [hikalkan/jtable#2045]
This jtable is very good, and abp collocation is very good, but the style is the reason why we give it up, can provide some good style?

**Comment by dm-Andy** [comment]
A lot of people said that jTable is very nice,but most use only in individual learning,many companies dont't choose it.
We want to spread jTable in the open community,let more and  more people to choose it,so if you can  provider some beautiful theme,i believe many people will choose it.
