### ISSUE TITLE
Angular 2 version

### ISSUE THREAD

**Issue by pantonis** [hikalkan/jtable#2056]
Do you have any plans to create this as native Angular 2 component with directives etc...

**Comment by hikalkan** [comment]
Hi,

Most Angular2 components were not ready when we develop this, and they are not mature yet. By the time, we want to replace components by native angular2 components where possible.

**Comment by pantonis** [comment]
Now that angular 2 has become angular 4 and it is mature enough are you planning to create it?

Thanks

**Comment by hikalkan** [comment]
Hi,

I just relarized that I had written my reply to jtable repository :) Sorry, we don't think to create jtable for angular at all.

**Comment by pantonis** [comment]
too bad :(
