### ISSUE TITLE
HOW CAN I USE VALIDATOR ENGINE AJAX CALL IN JTABLE PLUGIN

### ISSUE THREAD

**Issue by AModotti** [hikalkan/jtable#2070]
I can not understand how to use the validator engine with a JTable plugin.
I need to validate a JTable field using an ajax validation. I have read the documentation but can not pass the field value to the servlet, I always get NULL and I don't know why. Below my code. I'm standing for a week... :-( Thanks in advance.

**MY JTABLE JS CODE:**

azienda: {
        	title: 'Azienda',
                width: '10%',
                key : true,
                edit: true,
                create: true
            },
            primadescrizione: {
                title: 'Prima Descrizione',
                width: '30%'
            },
            secondadescrizione: {
                title: 'Seconda Descrizione',
                width: '30%'
            },
            aziendadefault: {
                title: 'Default',
                width: '10%',
                type: 'checkbox',
                values: { '0': 'No', '1': 'Si' },
                defaultValue: '0'
            },
            stato: {
                title: 'Stato',
                width: '10%',
                options: {'1': 'Attivo', '0': 'Non Attivo'},
                optionsSorting : 'value-desc'
            },
            creamenu: {
                title: 'Creazione Voci di Menu',
                width: '10%',
                type: 'checkbox',
                values: { '0': 'No', '1': 'Si' },
                defaultValue: '0',
                create: true,
                edit: false,
                list: false
            }
        },
        formCreated: function(event,data){
        	data.form.css('width', '600px');
        	data.form.find('input[name=primadescrizione]').css('width','400px');
        	data.form.find('input[name=secondadescrizione]').css('width','400px');
            data.form.find('input[name=azienda]').addClass('validate[required,ajax[ajaxCheckCompanyExists]]');
            data.form.find('input[name=primadescrizione]').addClass('validate[required]');
            data.form.validationEngine();
        },
        formSubmitting: function (event, data) {
            return data.form.validationEngine('validate');
        },
        formClosed: function (event, data) {
            data.form.validationEngine('hide');
            data.form.validationEngine('detach');
        },
        recordAdded: function (event, data) {
        	$('#div_managecompany').jtable('reload');
        }    
    });

**MY TRANSLATION FILE:**

"ajaxCheckCompanyExists": {
    "url": "ManageCompanies",
    "extraData": "action=check",
    "extraDataDynamic": ['#azienda'],
    "alertText": "* This company exists!",
    "alertTextOk": "All good!",
    "alertTextLoad": "* Validating, please wait"
}

**A TOPIC PART OF MY SERVLET:**

`if(action.equals("check")) {
	       		        		
        	String azienda = request.getParameter("azienda");  //<--PROBLEM: PASS NULL!!!!!
       
}`

**Comment by dasguptahirak** [comment]
If a field is marked as key, create and edit options are set to false as default
So remove key from "azienda" field
Then its value will be passed to servlet

**Comment by AModotti** [comment]
Thank you so much for the prompt reply, I was not hoping. Unfortunately, it does not work, I always return null. I add all my code in the hope that it will help. Thanks in advance.

**MY JS TABLE CODE**

$(document).ready(function() {
	
	$('#div_managecompany').jtable({
        title: 'Aziende Inserite',
        jqueryuiTheme: true,
        paging: true,
        sorting: true, 
        pageSize: 10,
        defaultSorting: 'Prima Descrizione ASC',
        actions: {
            listAction:   'ManageCompanies?action=getdata',
            createAction: 'ManageCompanies?action=insert&username=' + localStorage["username"],
            updateAction: 'ManageCompanies?action=update&username=' + localStorage["username"],
            deleteAction: 'ManageCompanies?action=delete&username=' + localStorage["username"]
        },
        fields: {
        	//TABELLA ANNIDATA
            mails: {
                title: '',
                width: '1%',
                sorting: false,
                edit: false,
                create: false,
                display: function (userData) {
                    //Create an image that will be used to open child table
                    var $img = $('<img src="images/down-arrow.png" width="18" height="18" title="Gestione Menu" />');
                    //Open child table when user clicks the image
                    $img.click(function () {
                        $('#div_managecompany').jtable('openChildTable',$img.closest('tr'),{
                        	title: userData.record.azienda + ' - ' + userData.record.primadescrizione + ' - ' + ' - Voci di Menu Inserite',
                            actions: {
                                listAction:   'ManageMenu?action=getdata&azienda=' + userData.record.azienda,
                                createAction: 'ManageMenu?action=insert&azienda=' + userData.record.azienda + '&username=' + localStorage["username"],
                                updateAction: 'ManageMenu?action=update&azienda=' + userData.record.azienda + '&username=' + localStorage["username"],
                                deleteAction: 'ManageMenu?action=delete&azienda=' + userData.record.azienda + '&username=' + localStorage["username"]
                            },
                            fields: {
                            	id: {
                                	title: 'id',
                                	width: '10%',
                                    key: true,
                                    edit: true,
                                    create: true,
                                },
                                azienda: {
                                    title: 'Azienda',
                                    width: '10%'
                                },
                                sequenza: {
                                    title: 'Sequenza',
                                    width: '10%'
                                },
                                tipo: {
                                    title: 'Tipo',
                                    width: '15%',
                                    options: {'H': 'Titolo', 'M': 'Voce di Menu'},
                                    optionsSorting : 'value'
                                },
                                primadescrizione: {
                                    title: 'Descrizione',
                                    width: '45%'
                                },
                                stato: {
                                    title: 'Stato',
                                    width: '10%',
                                    options: {'1': 'Attivo', '0': 'Non Attivo'},
                                    optionsSorting : 'value-desc'
                                },
                            },
                            formCreated: function(event,data){
                            	data.form.css('width', '600px');
                            	data.form.find('input[name=primadescrizione]').css('width','400px');
                            	data.form.find('input[name=id]').addClass('validate[required,custom[number]]');
                            	data.form.find('input[name=azienda]').addClass('validate[required,custom[number]]');
                            	data.form.find('input[name=sequenza]').addClass('validate[required,custom[number]]');
                                data.form.validationEngine();
                            },
                            formSubmitting: function (event, data) {
                                return data.form.validationEngine('validate');
                            },
                            formClosed: function (event, data) {
                                data.form.validationEngine('hide');
                                data.form.validationEngine('detach');
                            }
                        },function(data){ //opened handler
                            data.childTable.jtable('load');
                        });
                	});
                    //Return image to show on the person row
                    return $img;
                }
            },
            azienda: {     // <------ THE PROBLEM IS HERE!!! AZIENDA IS PASSED AS NULL IN CREATE!!
                title: 'Azienda',
                width: '10%'
            },
            primadescrizione: {
                title: 'Prima Descrizione',
                width: '30%'
            },
            secondadescrizione: {
                title: 'Seconda Descrizione',
                width: '30%'
            },
            aziendadefault: {
                title: 'Default',
                width: '10%',
                type: 'checkbox',
                values: { '0': 'No', '1': 'Si' },
                defaultValue: '0'
            },
            stato: {
                title: 'Stato',
                width: '10%',
                options: {'1': 'Attivo', '0': 'Non Attivo'},
                optionsSorting : 'value-desc'
            },
            creamenu: {
                title: 'Creazione Voci di Menu',
                width: '10%',
                type: 'checkbox',
                values: { '0': 'No', '1': 'Si' },
                defaultValue: '0',
                create: true,
                edit: false,
                list: false
            }
        },
        formCreated: function(event,data){
        	data.form.css('width', '600px');
        	data.form.find('input[name=primadescrizione]').css('width','400px');
        	data.form.find('input[name=secondadescrizione]').css('width','400px');
            data.form.find('input[name=azienda]').addClass('validate[required,ajax[ajaxCheckCompanyExists]]');
            data.form.find('input[name=primadescrizione]').addClass('validate[required]');
            data.form.validationEngine();
        },
        formSubmitting: function (event, data) {
            return data.form.validationEngine('validate');
        },
        formClosed: function (event, data) {
            data.form.validationEngine('hide');
            data.form.validationEngine('detach');
        },
        recordAdded: function (event, data) {
        	$('#div_managecompany').jtable('reload');
        }    
    });
	
	$('#div_managecompany').jtable('load');
		    
});

**MY TRANSLATION FILE**

"ajaxCheckCompanyExists": {
    "url": "ManageCompanies",
    "extraData": "action=check",
    "extraDataDynamic": ['#azienda'],
    "alertText": "* L'azienda esiste gia'",
    "alertTextOk": "Azienda validata",
    "alertTextLoad": "* Validazione azienda..."
}

** MY SERVLET CODE **

public class ManageCompanies extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public ManageCompanies() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
		PrintWriter out = response.getWriter();
		
		String action = request.getParameter("action");
		String sorting = request.getParameter("jtSorting");
		String startindex = request.getParameter("jtStartIndex");
		String pagesize = request.getParameter("jtPageSize");
		
		String orderby = "COID ASC";
		
		String TotalRecordCount = "";
		
		if(sorting != null){
			if(sorting.equals("codice ASC")){
				orderby = "COID ASC";
			}else if(sorting.equals("primadescrizione ASC")){
				orderby = "CODSC1 ASC";
			}else if(sorting.equals("secondadescrizione ASC")){
				orderby = "CODSC2 ASC";
			}else if(sorting.equals("aziendadefault ASC")){
				orderby = "CODEFAULT ASC";
			}else if(sorting.equals("stato ASC")){
				orderby = "COENABLED ASC";
			}else if(sorting.equals("codice DESC")){
				orderby = "COID DESC";
			}else if(sorting.equals("primadescrizione DESC")){
				orderby = "CODSC1 DESC";
			}else if(sorting.equals("secondadescrizione DESC")){
				orderby = "CODSC2 DESC";
			}else if(sorting.equals("aziendadefault ASC")){
				orderby = "CODEFAULT DESC";
			}else if(sorting.equals("stato DESC")){
				orderby = "COENABLED DESC";
			}
		}	
				
        if(action != null) {
        	                 
	        Connection conn = null;
	        PreparedStatement ps = null;
	        ResultSet rs = null;
	        String sql1 = "";
	        String sql2 = "";
	        
	        JSONObject jsonroot = new JSONObject();
	        	  
	        if(action.equals("getcompanies")) {
	        	
	        	        		    	
		    	sql1 = "SELECT COID,TRIM(CODSC1) "
		    	     + "  FROM F0201 "
		    		 + " WHERE COENABLED = '1' "
		    		 + "   AND CODELETED = '0' "
		    		 + "   AND CODEFAULT = '0' "
		    		 + " ORDER BY COID";

	        	try{
	        		
		            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
		            conn = DriverManager.getConnection(Settings.dbconnectionstring,Settings.dbusername,Settings.dbpassword);
			            
		            ps = conn.prepareStatement(sql1);
	
		            rs = ps.executeQuery();
	            		            	
		            while(rs.next()){
		            	
		            	JSONObject companies = new JSONObject();
		            	
		            	companies.put("azienda",rs.getString(1));
		            	companies.put("primadescrizione",rs.getString(2));
		            	
		            	jsonroot.append("Records",companies);
		            	
		            }
		            
		            rs.close();
		            ps.close();
		            		            	                        
		            out.println(jsonroot);
		            
		        }catch(Exception Ex) {
		        	try {
						jsonroot.append("Result", "ERROR");
			        	jsonroot.append("Message", Ex.getMessage());
			            out.print(jsonroot);
					} catch (JSONException e) {
						System.out.println(e.getMessage());
					}
		        }finally{
		            if (ps != null) {
		                try {
		                    ps.close();
		                } catch (SQLException e) {
		                    System.out.println(e.getMessage());
		                }
		            }
		
		            if (conn != null) {
		                try {
		                    conn.close();
		                } catch (SQLException e) {
		                    System.out.println(e.getMessage());
		                }
		            }
		
		        }
		        	
	        }else if(action.equals("getdata")) {
	        	
	        	sql1 = "SELECT COUNT(*) FROM F0201";
	        	        		    	
		    	sql2 = "SELECT COID,TRIM(CODSC1),TRIM(CODSC2),CODEFAULT,COENABLED "
		    	     + "  FROM (SELECT ROW_NUMBER() OVER (ORDER BY " + orderby + ") AS RowNumber,A.* FROM F0201 A) B "
		    		 + " WHERE B.RowNumber >" + startindex + " AND B.RowNumber <= " + startindex + pagesize 
		    		 + "   AND CODELETED = 0";

	        	try{
	        		
		            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
		            conn = DriverManager.getConnection(Settings.dbconnectionstring,Settings.dbusername,Settings.dbpassword);
		
		            ps = conn.prepareStatement(sql1);
		            
		            rs = ps.executeQuery();
		            
		            while (rs.next()) {
		            	TotalRecordCount = rs.getString(1);
					}
		            
		            ps = conn.prepareStatement(sql2);
	
		            rs = ps.executeQuery();
	            	
		            jsonroot.put("Result", "OK");
	            	jsonroot.put("TotalRecordCount", TotalRecordCount);
	            	
		            while(rs.next()){
		            	
		            	JSONObject companies = new JSONObject();
		            	
		            	companies.put("azienda",rs.getString(1));
		            	companies.put("primadescrizione",rs.getString(2));
		            	companies.put("secondadescrizione",rs.getString(3));
		            	companies.put("aziendadefault",rs.getString(4));
		            	companies.put("stato",rs.getString(5));
		            	
		            	jsonroot.append("Records",companies);
		            	
		            }
		            
		            rs.close();
		            ps.close();
		            		            	                        
		            out.println(jsonroot);
		            
		        }catch(Exception Ex) {
		        	try {
						jsonroot.append("Result", "ERROR");
			        	jsonroot.append("Message", Ex.getMessage());
			            out.print(jsonroot);
					} catch (JSONException e) {
						System.out.println(e.getMessage());
					}
		        }finally{
		            if (ps != null) {
		                try {
		                    ps.close();
		                } catch (SQLException e) {
		                    System.out.println(e.getMessage());
		                }
		            }
		
		            if (conn != null) {
		                try {
		                    conn.close();
		                } catch (SQLException e) {
		                    System.out.println(e.getMessage());
		                }
		            }
		
		        }
		        	
	        }else if(action.equals("insert")) {
	        	
	        	if(request.getParameter("azienda") != null) {
	        		
	                String azienda = request.getParameter("azienda");
	                String primadescrizione = request.getParameter("primadescrizione");
	                String secondadescrizione = request.getParameter("secondadescrizione");
	                String aziendadefault = request.getParameter("aziendadefault");
	                String stato = request.getParameter("stato");
	                String username = request.getParameter("username");
	                
	                if(primadescrizione == ""){
	                	primadescrizione = " ";
	            	};
	            	
	                if(secondadescrizione == ""){
	                	secondadescrizione = " ";
	            	};
	            	
	            	if(aziendadefault == null){
	            		aziendadefault = "0";
	            	};
	                    
		        	sql1 = "INSERT INTO F0201 "
		        		 + "            (COID,"
		        		 + "			 CODSC1,"
		        		 + "			 CODSC2,"
		        		 + "			 CODEFAULT,"
		        		 + "			 COENABLED,"
		        		 + "			 CODELETED,"
		        		 + "			 COINSERTDATE,"
		        		 + "			 COINSERTUSER,"
		        		 + "			 COUPDATEDATE,"
		        		 + "			 COUPDATEUSER,"
		        		 + "			 CODELETEDATE,"
		        		 + "			 CODELETEUSER)"
		        		 + "      VALUES(?,"
		        		 + "			 ?,"
		        		 + "			 ?,"
		        		 + "			 ?,"
		        		 + "			 ?,"
		        		 + "			 ?,"
		        		 + "			 TO_DATE(?,'DD/MM/YYYY HH24.MI.SS'),"
		        		 + "			 ?,"
		        		 + "			 ?,"
		        		 + "			 ?,"
		        		 + "			 ?,"
		        		 + "			 ?)";
			        		  	
		        	try{
		        		
			            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
			            conn = DriverManager.getConnection(Settings.dbconnectionstring,Settings.dbusername,Settings.dbpassword);
			
			            ps = conn.prepareStatement(sql1);
			            
			            ps.setString(1, azienda);
			            ps.setString(2, primadescrizione);
			            ps.setString(3, secondadescrizione);
			            ps.setString(4, aziendadefault);
			            ps.setString(5, stato);
			            ps.setString(6, "0");
			            ps.setString(7, Settings.getEventDate());
			            ps.setString(8, username);
			            ps.setString(9, null);
			            ps.setString(10, " ");
			            ps.setString(11, null);
			            ps.setString(12, " ");
			            
			            rs = ps.executeQuery();
			        					            
			            rs.close();
			            ps.close();
			            
			            JSONObject companies = new JSONObject();
			            
			            companies.put("azienda", azienda);
			            companies.put("primadescrizione", primadescrizione);
			            companies.put("secondadescrizione", secondadescrizione);
			            companies.put("stato", stato);
			            
			            jsonroot.put("Result", "OK");
			            jsonroot.put("Record", companies);
			            
			            out.println(jsonroot);
			            
			        }catch(Exception Ex) {
			        	try {
							jsonroot.append("Result", "ERROR");
				        	jsonroot.append("Message", Ex.getMessage());
				            out.print(jsonroot);
						} catch (JSONException e) {
							System.out.println(e.getMessage());
						}
			        }finally{
			            if (ps != null) {
			                try {
			                    ps.close();
			                } catch (SQLException e) {
			                    System.out.println(e.getMessage());
			                }
			            }
			
			            if (conn != null) {
			                try {
			                    conn.close();
			                } catch (SQLException e) {
			                    System.out.println(e.getMessage());
			                }
			            }
			
			        }
		        	
	        		if(request.getParameter("creamenu") != null) {
	        		        			 
	        			sql1 = "INSERT INTO F0200 "
	   		        		 + "	SELECT (SELECT MAX(MEID) FROM F0200) + ROWNUM,"
	   		        		 + "           ?,"
	   		        		 + "		   MESEQ,"
	   		        		 + "		   METYPE,"
	   		        		 + "           MEDSC1,"	
	   		        		 + "		   MEENABLED,"
	   		        		 + "		   MEDELETED,"
	   		        		 + "		   TO_DATE(?,'DD/MM/YYYY HH24.MI.SS'),"
	   		        		 + "		   ?,"
	   		        		 + "           ?,"
	   		        		 + "		   ?,"
	   		        		 + "		   ?,"
	   		        		 + "           ? "
	   		        		 + "      FROM F0200 WHERE MECOID = (SELECT COID FROM F0201 WHERE CODEFAULT = '1') ";
	        			
	        			try{
			        		
				            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
				            conn = DriverManager.getConnection(Settings.dbconnectionstring,Settings.dbusername,Settings.dbpassword);
				
				            ps = conn.prepareStatement(sql1);
				            
				            ps.setString(1, azienda);
				            ps.setString(2, Settings.getEventDate());
				            ps.setString(3, username);
				            ps.setString(4, null);
				            ps.setString(5, " ");
				            ps.setString(6, null);
				            ps.setString(7, " ");            
				            
				            rs = ps.executeQuery();
				        					            
				            rs.close();
				            ps.close();
				           
				            JSONObject nenu = new JSONObject();
				            				            
				            jsonroot.put("Result", "OK");
				            jsonroot.put("Record", nenu);
				            
				            out.println(jsonroot);
				            
				        }catch(Exception Ex) {
				        	try {
								jsonroot.append("Result", "ERROR");
					        	jsonroot.append("Message", Ex.getMessage());
					            out.print(jsonroot);
							} catch (JSONException e) {
								System.out.println(e.getMessage());
							}
				        }finally{
				            if (ps != null) {
				                try {
				                    ps.close();
				                } catch (SQLException e) {
				                    System.out.println(e.getMessage());
				                }
				            }
				
				            if (conn != null) {
				                try {
				                    conn.close();
				                } catch (SQLException e) {
				                    System.out.println(e.getMessage());
				                }
				            }
				
				        }
	
	        		}

	        	}
	        	
	        }else if(action.equals("update")) {
	        	
	        	if(request.getParameter("azienda") != null) {
	        		
	                String azienda = request.getParameter("azienda");
	                String primadescrizione = request.getParameter("primadescrizione");
	                String secondadescrizione = request.getParameter("secondadescrizione");
	                String aziendadefault = request.getParameter("aziendadefault");
	                String stato = request.getParameter("stato");
	                String username = request.getParameter("username");
	                
	                if(primadescrizione == ""){
	                	primadescrizione = " ";
	            	};
	            	
	                if(secondadescrizione == ""){
	                	secondadescrizione = " ";
	            	};
	                
	            	if(aziendadefault == null){
	            		aziendadefault = "0";
	            	};
	            	
		        	sql1 = "UPDATE F0201 "
		        		 + "   SET CODSC1 = ?,"
		        		 + "       CODSC2 = ?,"
		        		 + "       CODEFAULT = ?," 
		        		 + "       COENABLED = ?,"
		        		 + "  	   COUPDATEDATE = TO_DATE(?,'DD/MM/YYYY HH24.MI.SS')," 
		        		 + "	   COUPDATEUSER = ? "
				         + " WHERE COID = ? ";
					    	        	
		        	try{
		        		
			            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
			            conn = DriverManager.getConnection(Settings.dbconnectionstring,Settings.dbusername,Settings.dbpassword);
			
			            ps = conn.prepareStatement(sql1);
			            
			            ps.setString(1, primadescrizione);
			            ps.setString(2, secondadescrizione);
			            ps.setString(3, aziendadefault);
			            ps.setString(4, stato);
			            ps.setString(5, Settings.getEventDate());
			            ps.setString(6, username);
			            ps.setString(7, azienda);
			            
			            rs = ps.executeQuery();
			        					            
			            rs.close();
			            ps.close();
			            
			            jsonroot.put("Result", "OK");
			            
			            out.println(jsonroot);
			            
			        }catch(Exception Ex) {
			        	try {
							jsonroot.append("Result", "ERROR");
				        	jsonroot.append("Message", Ex.getMessage());
				            out.print(jsonroot);
						} catch (JSONException e) {
							System.out.println(e.getMessage());
						}
			        }finally{
			            if (ps != null) {
			                try {
			                    ps.close();
			                } catch (SQLException e) {
			                    System.out.println(e.getMessage());
			                }
			            }
			
			            if (conn != null) {
			                try {
			                    conn.close();
			                } catch (SQLException e) {
			                    System.out.println(e.getMessage());
			                }
			            }
			
			        }
	        	}

	        }else if(action.equals("delete")) {
	        	
	        	if(request.getParameter("azienda") != null) {
	        		
                    String azienda = request.getParameter("azienda");
                    String username = request.getParameter("username");
        		
		        	sql1 = "UPDATE F0201 "
		        		 + "   SET CODELETED = '1',"
		        		 + "  	   CODELETEDATE = TO_DATE(?,'DD/MM/YYYY HH24.MI.SS'),"
		        		 + "	   CODELETEUSER = ? "
				         + " WHERE COID = ? ";
				    	        	
		        	try{
		        		
			            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
			            conn = DriverManager.getConnection(Settings.dbconnectionstring,Settings.dbusername,Settings.dbpassword);
			
			            ps = conn.prepareStatement(sql1);
			            
			            ps.setString(1, Settings.getEventDate());
			            ps.setString(2, username);
			            ps.setString(3, azienda);
			            
			            rs = ps.executeQuery();
			        					            
			            rs.close();
			            ps.close();
			            
			            jsonroot.put("Result", "OK");
			            
			            out.println(jsonroot);
			            
			        }catch(Exception Ex) {
			        	try {
							jsonroot.append("Result", "ERROR");
				        	jsonroot.append("Message", Ex.getMessage());
				            out.print(jsonroot);
						} catch (JSONException e) {
							System.out.println(e.getMessage());
						}
			        }finally{
			            if (ps != null) {
			                try {
			                    ps.close();
			                } catch (SQLException e) {
			                    System.out.println(e.getMessage());
			                }
			            }
			
			            if (conn != null) {
			                try {
			                    conn.close();
			                } catch (SQLException e) {
			                    System.out.println(e.getMessage());
			                }
			            }
			
			        }
	        	}
		        	
	        }else if(action.equals("check")) {
	        		        		
        		String azienda = request.getParameter("azienda");  // <------ THE PROBLEM IS HERE!!! AZIENDA IS PASSED AS NULL
                
            	sql1 = "SELECT COUNT(*) " 
                     + "  FROM F0201 " 
                     + " WHERE COENABLED = '1' "
                     + "   AND CODELETED = '0' "
                     + "   AND COID = ? ";
            	        	
            	try{
            		
    	            Class.forName("oracle.jdbc.driver.OracleDriver").newInstance();
    	            conn = DriverManager.getConnection(Settings.dbconnectionstring,Settings.dbusername,Settings.dbpassword);
    	
    	            ps = conn.prepareStatement(sql1);

    	            ps.setString(1, azienda);
    	            
    	            rs = ps.executeQuery();
    	            
    	            while(rs.next()){
    	            	if(rs.getString(1).equals("0")){
    	            		jsonroot.put("azienda",new Boolean(true));
    	            	}else{
    	            		jsonroot.put("azienda",new Boolean(false));
    	            	}	
    	            }
    	            
    	            rs.close();
    	            ps.close();
    	            
    	            out.println(jsonroot);
    	            
    	        }catch(Exception Ex) {
    	
    	            out.print(Ex.getMessage());
    	
    	        }finally{
    	
    	            if (ps != null) {
    	                try {
    	                    ps.close();
    	                } catch (SQLException e) {
    	                    System.out.println(e.getMessage());
    	                }
    	            }
    	
    	            if (conn != null) {
    	                try {
    	                    conn.close();
    	                } catch (SQLException e) {
    	                    System.out.println(e.getMessage());
    	                }
    	            }

    	        }
        	}

        }
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}

**Comment by AModotti** [comment]
Solved by myself!
I modified the file jquery.validationEngine.js in the ajax function section so that you also accept searched items by name and not just by id. If you use the validator engine with Jtable plugin this is useful brcause jable does not allow to assign an id to the fields
