### ISSUE TITLE
Column will show One when same value

### ISSUE THREAD

**Issue by Hasibaziz** [hikalkan/jtable#2107]
Please see the below screen shot.
![image](https://user-images.githubusercontent.com/5820022/30693703-8e8b3d10-9ef2-11e7-8645-f34a99d94973.png)

Any help/suggestion is appreciated. Thanks.

**Comment by Hasibaziz** [comment]
I have used that way but it is not working. Please help me.
var mainMergingData = "";
var mainMergingCell;
$('RecordsContainer').jtable({
    ..................................
     SSC: {
                    title: ' S. S. C',
                    width: '10%',
                    recordsLoaded: function (event, data) {
                        // sorting on the base of column one
                        for (var i = 0; i < data.records.length; i++) {
                            var rec = data.records[i];
                            var $row = $('RecordsContainer').jtable('getRowByKey', rec.Id);
                            if (rec.SSC== mainMergingData) {
                                $row.find('td')[0].remove();
                                mainMergingCell, rowSpan++;
                            } else {
                                mainMergingCell = $row.find('td')[0]; // column what ever  your column index
                                mainMergingData = rec.SSC;
                            }
                        }
                    }   
                }
 });

**Comment by sheryever** [comment]
`recordsLoaded` is a jtable level event, you are using it in the field options.

**Comment by Hasibaziz** [comment]
Thank your for your help, but how can I use? Can you show me one example, Plz

**Comment by sheryever** [comment]
[recordsLoaded](http://www.jtable.org/ApiReference/Events#event-recordsLoaded) runs once when page is rendered, which means this event will be raise after the creation of table.


```javascript
   var mainMergingData = "";
   var mainMergingCell;
   $('jtableContainer').jtable({
       ....
          fields: {
              Id: {
                  key: true,
                  create: false,
                  edit: false,
                  list: false
                  },
              Name: {
                  title: 'Course name',
                  width: '40%'
               },
              OtherColumn1: {
                  title: 'Column 1',
                  width: '30%',
              },
             OtherColumn2: {
                  title: 'Column 2',
                  width: '30%',
             }
       },
       recordsLoaded: function (event, data){
          // sorting on the base of column one
          for(var i = 0; i < data.records.length; i++)
          {
              var rec = data.records[i];
              var $row = $('jtableContainer').jtable('getRowByKey', rec.Id);
              if (rec.Name == mainMergingData){
                  $row.find('td')[0].remove();
                  mainMergingCell,rowSpan++; 
              } else {
                   mainMergingCell = $row.find('td')[0]; // column what ever  your column index
                   mainMergingData = rec.Name;
              }
          }
       }   
    });
```

**Comment by Hasibaziz** [comment]
Brother, I have applied but not working. Is there any other issue?

**Comment by sheryever** [comment]
share your code

**Comment by Hasibaziz** [comment]
Please see below of my codes and the output screen shot.
- $(document).ready(function () {
        var mainMergingData = "";
        var mainMergingCell;

        $('#RecordsContainer').jtable({
            title: 'Efficiency Section Wise',
            paging: true,
            footer: true,
            pageSize: 20,
            sorting: false,
            defaultSorting: 'Name ASC',
            actions: {
                listAction: '<%=Url.Content("~/Production/EfficiencyList") %>'
            },
            toolbar: {
                hoverAnimation: true, //Enable/disable small animation on mouse hover to a toolbar item.
                hoverAnimationDuration: 80, //Duration of the hover animation.
                hoverAnimationEasing: undefined, //Easing of the hover animation. Uses jQuery's default animation ('swing') if set to undefined.
                items: [
                 {
                     // text: $('#SearchContainer')
                 }, {
                     tooltip: 'Click here to Exprot on PDF',
                     icon: "../../Content/images/pdf24.png",
                     text: 'Export to PDF',
                     click: function () {
                         window.open("/Production/EfficiencyReport");
                     }
                 }
                ]
            },
            fields: {
                FactoryLot: {
                    title: 'Style',
                    width: '10%'
                },
                ProductionQty: {
                    title: 'Total Qty',
                    width: '10%',
                    create: false,
                    edit: false,
                    display: function (data) {
                        //return "£ " + data.record.SAH;
                        return data.record.ProductionQty;
                    },
                    footer: function (data) {
                        var total = 0;
                        $.each(data.Records, function (index, record) {
                            total += Number(record.ProductionQty);
                        });
                        //return ("£" + total.toFixed(2));
                        return (total.toFixed(2));
                    }
                },
                SMV: {
                    title: 'SMV',
                    width: '10%',
                    create: false,
                    edit: false,
                    display: function (data) {
                        //return "£ " + data.record.SAH;
                        return data.record.SMV;
                    },
                    footer: function (data) {
                        var total = 0;
                        $.each(data.Records, function (index, record) {
                            total += Number(record.SMV);
                        });
                        //return ("£" + total.toFixed(2));
                        return (total.toFixed(2));
                    }
                },
                ProductionMin: {
                    title: 'T.Production(Min)',
                    width: '12%',
                    create: false,
                    edit: false,
                    display: function (data) {
                        //return "£ " + data.record.SAH;
                        return data.record.ProductionMin;
                    },
                    footer: function (data) {
                        var total = 0;
                        $.each(data.Records, function (index, record) {
                            total += Number(record.ProductionMin);
                        });
                        //return ("£" + total.toFixed(2));
                        return (total.toFixed(2));
                    }
                },
                SAH: {
                    title: 'SAH',
                    width: '7%',
                    create: false,
                    edit: false,
                    display: function (data) {
                        //return "£ " + data.record.SAH;
                        return data.record.SAH;
                    },
                    footer: function (data) {
                        var total = 0;
                        $.each(data.Records, function (index, record) {
                            total += Number(record.SAH);
                        });
                        //return ("£" + total.toFixed(2));
                        return (total.toFixed(2));
                    }
                },
                AvailableMin: {
                    title: 'Available(Min)',
                    width: '15%'
                },
                LostMin: {
                    title: 'Lost Min',
                    width: '10%'
                },
                StdEfficiency: {
                    title: 'Std Efficiency',
                    width: '10%',
                    create: false,
                    edit: false,
                    display: function (data) {
                        //return "£ " + data.record.SAH;
                        return data.record.StdEfficiency;
                    },
                    footer: function (data) {
                        var total = 0;
                        $.each(data.Records, function (index, record) {
                            total += Number(record.StdEfficiency);
                        });
                        //return ("£" + total.toFixed(2));
                        return ((total * 100).toFixed(2) + "%");
                    }
                },
                OverallEfficiency: {
                    title: 'Overall Efficiency',
                    width: '13%',
                    create: false,
                    edit: false,
                    display: function (data) {
                        //return "£ " + data.record.SAH;
                        return data.record.OverallEfficiency;
                    },
                    footer: function (data) {
                        var total = 0;
                        $.each(data.Records, function (index, record) {
                            total += Number(record.OverallEfficiency);
                        });
                        //return ("£" + total.toFixed(2));
                        return ((total * 100).toFixed(2) + "%");
                    }
                },
                CurrentDate: {
                    title: 'Date',
                    width: '15%',
                    type: 'date',
                    displayFormat: 'mm/dd/yy'
                }
            },
            recordsLoaded: function (event, data) {
                // sorting on the base of column one
                alert("Hello");
                for (var i = 0; i < data.records.length; i++) {
                    var rec = data.records[i];
                    var ID = rec.FactoryLot;
                    //mainMergingData = rec.LostMin;
                    var $row = $('#RecordsContainer').jtable('getRowByKey', ID);                    
                    if (rec.LostMin == mainMergingData) {
                        alert("Hello:-" + ID);
                        $row.find('td')[0].remove();
                        mainMergingCell, rowSpan++;                        
                    } else {                       
                        mainMergingCell = $row.find('td')[0]; // column what ever  your column index
                        mainMergingData = rec.LostMin;
                    }
                }
            }
        });
        $('#ViewData').click(function (e) {
            e.preventDefault();
            $('#RecordsContainer').jtable('load', {
                CDate: $('.datefield').val(),
                Sitem: $('.SField').val()
            });
        });
    });
![image](https://user-images.githubusercontent.com/5820022/31368747-740691e8-ada1-11e7-8dcc-e9249cede81e.png)

**Comment by sheryever** [comment]
As I understand you want to merge LostMin column in your table.  I am just fixing the code of recordsLoaded event. Read my comments in the code

```javascript
      recordsLoaded: function (event, data) {
          // sorting on the based on LostMin  column 

          for (var i = 0; i < data.records.length; i++) {
              var rec = data.records[i];
              var ID = rec.FactoryLot;
              var $row = $('#RecordsContainer').jtable('getRowByKey', ID);                    

              if (rec.LostMin == mainMergingData) {
                  $row.find('td')[6].remove();
                  mainMergingCell.rowSpan++;      // This was the mistake in my own code. You need to update rowSpan property of mainMergingCell.
              } else {                       
                  mainMergingCell = $row.find('td')[6]; // column what ever  your column index
                  mainMergingData = rec.LostMin;
              }
          }
      }
```

- **Whenever you use the merging, you need to switch off the paging otherwise your marging will be wrong**
- **Whenever you use the footer, you need to switch off the paging otherwise your calculation will be wrong or you can calculate the footer values on server and return the values with your response**

**Comment by Hasibaziz** [comment]
I got your point but still not working because I put if (rec.LostMin == mainMergingData) where I have declared var mainMergingData = ""; as for your coding but how it will check because rec.LostMin have value every time where as mainMergingData is null. Can you plz check?

**Comment by Hasibaziz** [comment]
`if (rec.LostMin == mainMergingData)`

> if (rec.LostMin == mainMergingData)

- if (rec.LostMin == mainMergingData)

**Comment by Hasibaziz** [comment]
if you have any project then please send me screen shot with Example.

**Comment by Hasibaziz** [comment]
Got the solution. Need to manage from Query side.
