### ISSUE TITLE
How to detect table event is raised inside Extend class file 

### ISSUE THREAD

**Issue by lalwanikamal165** [hikalkan/jtable#2113]
Hi i want to detect if **recordsLoaded**  event is fired on table and if event firedon table then i want to do some operation in my extend class

(function ($) {
var base = {
_create: $.hik.jtable.prototype._create
}

     //extension members
    $.extend(true, $.hik.jtable.prototype, {

        /************************************************************************
    * DEFAULT OPTIONS / EVENTS                                              *
    *************************************************************************/
        options: {

            //Options
            multiPageSelect: {idsInSelection:[] },
       
            }
        },

// **i want to check if this event is fired then do some operation**
  recordsLoaded: function(){
var a = options.multiPageSelect.idsInSelection;
// do some opration with a
alert(a);
}

**Comment by sheryever** [comment]
Overwrite the event of the base class.

You can see that in any of extension of jtable.

```javascript
var base = {
    _create: $.hik.jtable.prototype._create,
    _onRecordsLoaded: $.hik.jtable.prototype._onRecordsLoaded
};

$.extend(true, $.hik.jtable.prototype, {
    /* Overrides _onRecordsLoaded method to to do paging specific tasks.
    *************************************************************************/
    _onRecordsLoaded: function (data) {
        base._onRecordsLoaded.apply(this, arguments);
        //You code
    },
}
```

**Comment by lalwanikamal165** [comment]
Thank you .. :-)
