### ISSUE TITLE
jtable -plugin options not loading.

### ISSUE THREAD

**Issue by alexmygh** [hikalkan/jtable#2140]
Dears,

 I am still getting  "Can not load options for field device_id"
Below is my (1) sql query and (2) output of the json print.
Please help me out.

fields: {
                  recid: {
                    title: 'ID',
                    width: '1%',
                    options: '/pmrAdmin/jsontest.php'
                  
                },
                device_d: {
                    title: 'SITE NAME',
                    width: '1%',
                    options: '/pmrAdmin/jsontest.php'
                  
                },

Many thanks

(1)This is my query 
  // enter your sql query
    $sql = ("SELECT recid, device_id FROM v_credit_site133 UNION SELECT recid, device_id FROM v_credit_site62");

       //$row = mysql_fetch_array($sql);
		//$recordCount = $row['RecordCount'];

//execute query
$result = $mysqli->query($sql);

//loop through the returned data
$rows = array();

foreach ($result as $row) 
//while($row = mysql_fetch_array($result))

{
    $rows[] = $row;
	//$eil=array();
    //$eil["DisplayText"]=$row['DisplayText'];
    //$eil["Value"]=$row['DisplayText'];
	//$jTableResult[] = $row;
}

$jTableResult = array();
$jTableResult['Result'] = "OK";
$jTableResult['Options']=$rows;
print json_encode($jTableResult);

?>

(2)This is my print json_encode OUTPUT

{"Result":"OK","Options":[{"recid":"1","device_id":"133"},{"recid":"2","device_id":"133"},{"recid":"3","device_id":"133"},{"recid":"4","device_id":"133"},{"recid":"5","device_id":"133"},{"recid":"6","device_id":"133"},{"recid":"7","device_id":"133"},{"recid":"8","device_id":"133"},{"recid":"9","device_id":"133"},{"recid":"10","device_id":"133"},{"recid":"11","device_id":"133"},{"recid":"12","device_id":"133"},{"recid":"13","device_id":"133"},{"recid":"14","device_id":"133"},{"recid":"15","device_id":"133"},{"recid":"16","device_id":"133"},{"recid":"17","device_id":"133"},{"recid":"18","device_id":"133"},{"recid":"19","device_id":"133"},{"recid":"20","device_id":"133"},{"recid":"21","device_id":"133"},{"recid":"22","device_id":"133"},{"recid":"23","device_id":"133"},{"recid":"24","device_id":"133"},{"recid":"23","device_id":"62"},{"recid":"24","device_id":"62"},{"recid":"25","device_id":"62"},{"recid":"26","device_id":"62"},{"recid":"27","device_id":"62"},{"recid":"28","device_id":"62"},{"recid":"31","device_id":"62"},{"recid":"32","device_id":"62"},{"recid":"33","device_id":"62"},{"recid":"36","device_id":"62"},{"recid":"37","device_id":"62"},{"recid":"38","device_id":"62"},{"recid":"39","device_id":"62"},{"recid":"40","device_id":"62"},{"recid":"41","device_id":"62"},{"recid":"42","device_id":"62"},{"recid":"43","device_id":"62"},{"recid":"44","device_id":"62"},{"recid":"45","device_id":"62"},{"recid":"46","device_id":"62"},{"recid":"47","device_id":"62"}]}

**Comment by sheryever** [comment]
Your returned json must formatted as following, otherwise it will not work.

```javascript

{"Result":"OK", "Options":[{"DisplayText":"1","Value":"133"},{"DisplayText":"2","Value":"133"},{"DisplayText":"3","Value":"133"}]

```

**Comment by alexmygh** [comment]
@Sheryever, Many thanks. I have than the correction and options are loaded now.
However I still have one more issue. When I click on the "Load Records" nothing happens. 
I am using jquery.js version  jQuery JavaScript Library v1.12.4.
Please need your support.




<div class="filtering">
    <form>


    Search: <input type="text" name="name" id="name" />
        Siteid: 
        <select id="device_id" name="device_id">
            <option selected="selected" value="0">All sites</option>
            <option value="1">133</option>
            <option value="2">62</option>
            
        </select>
        <button type="submit" id="LoadRecordsButton">Load records</button>
    </form>
</div>

<div id="StudentTableContainer"></div>

<script type="text/javascript">
    
 $( document ).ready(function() {
  $('#StudentTableContainer').jtable({
                

        
             //unAuthorizedRequestRedirectUrl: true,
            title: 'testing range selection (KWh)',
             paging: true,
            sorting: true,
            defaultSorting: 'Name ASC',
             pageList:'normal',
            pageSize: 2,
        
            selecting: true,
             selectingCheckboxes: true,
              selectOnRowClick:true,
     
            columnResizable: true,
            animationsEnabled: true,
             columnSelectable:true,
             dialogShowEffect: true,
         loadingAnimationDelay: 500,
ajaxSettings: {
           
            type: 'GET',
            dataType: 'json'
        },
toolbar: {
          
        hoverAnimation: true,
        hoverAnimationDuration: 60,
    items: [{
         tooltip: 'Click here to export this table to excel',
        icon: '',
        text: 'Export To Excel',
        click: function () { 
            window.open('data:application/vnd.ms-excel,' + encodeURIComponent($('#StudentTableContainer').html()));
        }
    },
    {
        
        click: function () {
            //perform your custom job...
        }
    }]
},
             


                actions: {
                listAction: 'dycredit.php?action=list'
        
               
                
  
            },
            fields: {
              device_id: {
            key: true,
            create: false,
            edit: false,
            list: false
          },
                //recid=device_id   
                recid: {

                    title: 'SITE NAME',
                    width: '1%',
                    options: 'http://localhost/pmrAdmin/jsontest.php'
                  
                },

                     from_date: {
                    title: 'FROM_DATE',
                    width: '1%'
                },

                 to_date: {
                    title: 'TO_DATE',
                    width: '1%'
                },
                
                 
                  total_kwh: {
                    title: 'TOTAL_KWH',
                    width: '1%'
                },
                
                 Usuage_KWH: {
                    title: 'CREDIT-CONSUMP(kWh)',
                    width: '1%'
                }

            }
        });


 //Re-load records when user click 'load records' button.
        $('#LoadRecordsButton').click(function (e) {
            e.preventDefault();
            $('#StudentTableContainer').jtable('load', {
                name: $('#name').val(),
                device_id: $('#device_id').val()
            });
        });
 
        //Load all records when page is first shown
        $('#LoadRecordsButton').click();




});




</script>

**Comment by sheryever** [comment]
First edit your comment and re-post your javascript in your comment, I cannot read it.

If you are using chrome then open Developers Tools (Press: F12 key), navigate to Network tab, click you LoadRecordButton and check that any new request appear in the Network Activity.

If there is any new activity then click it and check the Preview tab in the detail panel, that will show you the result. check are you receiving any data?

**Comment by alexmygh** [comment]
@Sheryever, many thanks.
(1)There is an activity as indicated in the screenshort.
(2) Below is my javascript

<script type="text/javascript">
 $( document ).ready(function() {
  $('#StudentTableContainer').jtable({
                

        
             unAuthorizedRequestRedirectUrl: true,
            title: 'testing range selection (KWh)',
             paging: true,
            sorting: true,
            defaultSorting: 'SITEID ASC',
             pageList:'normal',
            pageSize: 2,
        
            selecting: true,
             selectingCheckboxes: true,
              selectOnRowClick:true,
     
            columnResizable: true,
            animationsEnabled: true,
             columnSelectable:true,
             dialogShowEffect: true,
         loadingAnimationDelay: 500,
ajaxSettings: {
             async: true,   
           
            type: 'GET',
            dataType: 'json',
            contentType: "application/json"
        },
toolbar: {
          
        hoverAnimation: true,
        hoverAnimationDuration: 60,
    items: [{
         tooltip: 'Click here to export this table to excel',
        icon: '',
        text: 'Export To Excel',
        click: function () { 
            window.open('data:application/vnd.ms-excel,' + encodeURIComponent($('#StudentTableContainer').html()));
        }
    },
    {
        
        click: function () {
            //perform your custom job...
        }
    }]
},
             


                actions: {
                listAction: 'dycredit.php?action=list'
        
               
                
  
            },
            fields: {
              device_id: {
            key: true,
            create: false,
            edit: false,
            list: false
          },
                //recid=device_id   
                recid: {

                    title: 'SITEID',
                    width: '1%',
                    options: 'http://localhost/pmrAdmin/jsontest.php'
                  
                },

                     from_date: {
                    title: 'FROM_DATE',
                    width: '1%'
                },

                 to_date: {
                    title: 'TO_DATE',
                    width: '1%'
                },
                
                 
                  total_kwh: {
                    title: 'TOTAL_KWH',
                    width: '1%'
                },
                
                 Usuage_KWH: {
                    title: 'CREDIT-CONSUMP(kWh)',
                    width: '1%'
                }

            }
        });


 //Re-load records when user click 'load records' button.
        $('#LoadRecordsButton').click(function (e) {
            e.preventDefault();
            $('#StudentTableContainer').jtable('load', {
                name: $('#name').val(),
                device_id: $('#device_id').val()
            });
        });
 
        //Load all records when page is first shown
        $('#LoadRecordsButton').click();




});




</script>

**Comment by alexmygh** [comment]
(1)There is an activity as indicated in the screenshort.
(2) Below is my javascript
<script type="text/javascript">
    
 $( document ).ready(function() {
  $('#StudentTableContainer').jtable({
                

        
             //unAuthorizedRequestRedirectUrl: true,
            title: 'testing range selection (KWh)',
             paging: true,
            sorting: true,
            defaultSorting: 'SITEID ASC',
             pageList:'normal',
            pageSize: 2,
        
            selecting: true,
             selectingCheckboxes: true,
              selectOnRowClick:true,
     
            columnResizable: true,
            animationsEnabled: true,
             columnSelectable:true,
             dialogShowEffect: true,
         loadingAnimationDelay: 500,
ajaxSettings: {
             async: true,   // this will solve the problem
           
            type: 'GET',
            dataType: 'json',
            contentType: "application/json"
        },
toolbar: {
          
        hoverAnimation: true,
        hoverAnimationDuration: 60,
    items: [{
         tooltip: 'Click here to export this table to excel',
        icon: '',
        text: 'Export To Excel',
        click: function () { 
            window.open('data:application/vnd.ms-excel,' + encodeURIComponent($('#StudentTableContainer').html()));
        }
    },
    {
        
        click: function () {
            //perform your custom job...
        }
    }]
},
             


                actions: {
                listAction: 'dycredit.php?action=list'
        
               
                
  
            },
            fields: {
              device_id: {
            key: true,
            create: false,
            edit: false,
            list: false
          },
                //recid=device_id   
                recid: {

                    title: 'SITEID',
                    width: '1%',
                    options: 'http://localhost/pmrAdmin/jsontest.php'
                  
                },

                     from_date: {
                    title: 'FROM_DATE',
                    width: '1%'
                },

                 to_date: {
                    title: 'TO_DATE',
                    width: '1%'
                },
                
                 
                  total_kwh: {
                    title: 'TOTAL_KWH',
                    width: '1%'
                },
                
                 Usuage_KWH: {
                    title: 'CREDIT-CONSUMP(kWh)',
                    width: '1%'
                }

            }
        });


 //Re-load records when user click 'load records' button.
        $('#LoadRecordsButton').click(function (e) {
            e.preventDefault();
            $('#StudentTableContainer').jtable('load', {
                name: $('#name').val(),
                device_id: $('#device_id').val()
            });
        });
 
        //Load all records when page is first shown
        $('#LoadRecordsButton').click();




});




</script>

**Comment by alexmygh** [comment]
@sheryever many thanks for your support.

(1)There is an activity as indicated in the screenshort.
attached.
![network_activity](https://user-images.githubusercontent.com/35569563/35214948-af8969b0-ff5a-11e7-8713-ede9e5be49e8.JPG)

(2) Below is my javascript

  <script type="text/javascript">
 $( document ).ready(function() {
  $('#StudentTableContainer').jtable({
//unAuthorizedRequestRedirectUrl: true,
            title: 'testing range selection (KWh)',
             paging: true,
            sorting: true,
            defaultSorting: 'SITEID ASC',
             pageList:'normal',
            pageSize: 2,
        
            selecting: true,
             selectingCheckboxes: true,
              selectOnRowClick:true,
            columnResizable: true,
            animationsEnabled: true,
             columnSelectable:true,
             dialogShowEffect: true,
         loadingAnimationDelay: 500,
ajaxSettings: {
             async: true,   // this will solve the problem
            type: 'GET',
            dataType: 'json',
            contentType: "application/json"
        },
toolbar: {      
        hoverAnimation: true,
        hoverAnimationDuration: 60,
    items: [{
         tooltip: 'Click here to export this table to excel',
        icon: '',
        text: 'Export To Excel',
        click: function () { 
            window.open('data:application/vnd.ms-excel,' + encodeURIComponent($('#StudentTableContainer').html()));
        }
    },
    {
        
        click: function () {
            //perform your custom job...
        }
    }]
},

actions: {
                listAction: 'dycredit.php?action=list'
        
               
                
  
            },
            fields: {
              device_id: {
            key: true,
            create: false,
            edit: false,
            list: false
          },
                //recid=device_id   
                recid: {

                    title: 'SITEID',
                    width: '1%',
                    options: 'http://localhost/pmrAdmin/jsontest.php'
                  
                },

                     from_date: {
                    title: 'FROM_DATE',
                    width: '1%'
                },

                 to_date: {
                    title: 'TO_DATE',
                    width: '1%'
                },
                
                 
                  total_kwh: {
                    title: 'TOTAL_KWH',
                    width: '1%'
                },
                
                 Usuage_KWH: {
                    title: 'CREDIT-CONSUMP(kWh)',
                    width: '1%'
                }

            }
        });
 //Re-load records when user click 'load records' button.
        $('#LoadRecordsButton').click(function (e) {
            e.preventDefault();
            $('#StudentTableContainer').jtable('load', {
                name: $('#name').val(),
                device_id: $('#device_id').val()
            });
        });
        //Load all records when page is first shown
        $('#LoadRecordsButton').click();
});
</script>
