### ISSUE TITLE
Child table not populating data (No data available )

### ISSUE THREAD

**Issue by abhijit-mishra2003** [hikalkan/jtable#2150]
Hi All,

I been trying to add an on-click to expand a cell into a child table. But data doesn't see to get loaded. 
I understand there are examples and many have already fixed this, but I still cant figure out what's wrong with my code.

Please help. Below is a code snap.

```
 //Prepare jtable plugin
    $('#MQReposTable').jtable({
        title: 'The MQ Repos v0.1',
        paging: true,
        pageSize: 10,
        sorting: true,
        defaultSorting: 'APP ASC',
        selecting: true, //Enable selecting
        multiselect: false, //Allow multiple selecting
        selectingCheckboxes: false, //Show checkboxes on first column
        selectOnRowClick: true, //Enable this to only select using checkboxes
        actions: 
        {
            listAction: 'CRUDController?action=listByFilter',
            createAction:'CRUDController?action=create',
            updateAction: 'CRUDController?action=update',
            deleteAction: 'CRUDController?action=delete'
  
        },
        toolbar: 
        {
            items: [ {tooltip: 'Export this table to excel', icon: 'imgs/excel.png', text: 'Export to Excel', click: function (){  alert('This is yet to be implemented.'); } }]
        },
        fields: 
        {
        	App_ID: {key: true, create: false,edit: false,list: false},
        	App_ID: {title:'ID', key: true,list: true,create:true,width: '10px'},
        	REGION: {title:'ENV',edit: true, list: false},
        	APP_NAME: {title:'APPLICATION',width: '40%',edit:true},
        	APP_ACRONYM: {title:'Acronym',width: '30px',edit:true },
        	QMGR:  {title:'QMGR', width: '12px',edit: true},
        	Primary_server:{title:'P_Server',	width: '72px',edit: true},
        	Secondary_server:{title:'S_Server',	width: '72px',edit: true},
        	OS_TYPE:{title:'OS',width: '12px',edit: true},
        	Client_Version:{title:'MQ Client Ver',width: '12px',edit: true},
        	APP_TECHNOLOGY:{title:'TECHNOLOGY',width: '12px',edit: true},
        	VERSION:{title:'VERSION',width: '12px',edit: true},
        	REGION:{title:'REGION',width: '12px',edit: true},
        	SEG_ID:{title:'Segment',width: '12px',edit: true},
            Others: { title: 'More', width: '12px', sorting: false, edit: false, create: false,listClass: 'child-opener-image-column',
                display: function (app) {
                    //Create an image that will be used to open child table
                	console.log(JSON.stringify(app));
                    var $img = $('<img class="child-opener-image" src="imgs/list_metro.png" title="Expand View" />');

                    //Open child table when user clicks the image
                    $img.click(function () {

                        $('#MQReposTable').jtable('openChildTable',
                                $img.closest('tr'),
                                {
                                    title: app.record.APP_NAME + ' - Details',
                                    actions: 
                                    {
                                        listAction: 'CRUDController?action=getAppById' ,
                                        deleteAction: '/Demo/DeletePhone',
                                        updateAction: '/Demo/UpdatePhone',
                                        createAction: 'CRUDController?action=getAppById?App_ID=' + app.record.App_ID
                                    },
                                    fields: 
                                    {
                                    	APP_NAME: {title:'Application Name', key: true,list: true,create:true,width: '5px', defaultValue: app.record.APP_NAME},
                                        QMGR:{ title: 'QMGR', width: '5px',edit: true}
                                    } 
                                
                              }, 
                              function (data) { //opened handler
                                    data.childTable.jtable('load');
                        });
                    });
                    //Return image to show on the person row
                    return $img;
                }
            },
        },


``````

JSON for child is 

`{"Result":"OK","Record":{"App_ID":1,"APP_NAME":"APP1","APP_ACRONYM":"APP1","QMGR":"ABC","Primary_server":"servers1","Secondary_server":"server2","OS_TYPE":"OEL","Client_Version":9.0.0.0","APP_TECHNOLOGY":"Java","VERSION":"1.7","REGION":"ABC"}}
`

Kindly suggest. Though my parent table loads, I have spend days with no clue why child table not working. 

Thanks in advance.

**Comment by dasguptahirak** [comment]
@Abhijit

You are doing well. You have to just put 

CRUDController?action=getAppById?App_ID=' + app.record.App_ID

for listAction

**Comment by abhijit-mishra2003** [comment]
@dasguptahirak 
Thanks for reading my code. Currently getAppById is a dummy function right now which simply returns a fixed JSON (having ID=1). Even if I click the row with the same app ID, it still does not populate data in child row.

```
		actions: 
		{
			listAction: 'CRUDController?action=getAppById?App_ID='+ app.record.App_ID,
			deleteAction: '/Demo/DeletePhone',
			updateAction: '/Demo/UpdatePhone',
			createAction: 'CRUDController?action=getAppById?App_ID=' + app.record.App_ID
		},
		fields: 
		{
			APP_NAME: 	{title:'App Name', key: true,list: true,create:true,width: '5px'}
		}
```
The response from this function is still the same.

`
{"Result":"OK","Record":{"App_ID":1,"APP_NAME":"APP1","APP_ACRONYM":"APP1","QMGR":"ABC","Primary_server":"server1","Secondary_server":"server2","OS_TYPE":"OEL","Client_Version":"9.0.0.0","APP_TECHNOLOGY":"Java","VERSION":"1.7","REGION":"ABC"}}
`
Is there anything else I'm missing?

**Comment by dasguptahirak** [comment]
Please share your method getAppById

**Comment by abhijit-mishra2003** [comment]
This is how my dummy method looks like. Its hard coded to return this fixed JSON in string format.


```
else if(action.startsWith("getAppById?App_ID="))
{
	try{						
	//Fetch Data from User Table (dummy returning fixed JSON for testing)
	String listData = 
			"{\"Result\":\"OK\",\"Record\":" + 
			"{\"App_ID\":1,\"APP_NAME\":\"3PLA\",\"APP_ACRONYM\":\"3PLA\",\"QMGR\":\"FFLGE1CU06\",\"Primary_server\":\"ausul1mqa04.us.dell.com\",\"Secondary_server\":\"ausul1mqb04.us.dell.com\",\"OS_TYPE\":\"OEL\",\"Client_Version\":\"7.5.0.5\",\"APP_TECHNOLOGY\":\"Java\",\"VERSION\":\"1.7\",\"REGION\":\"DAO\"}" + 
			"}";
	response.getWriter().print(listData);
	}
	catch(Exception ex)
	{
		String error="{\"Result\":\"ERROR\",\"Message\":"+ex.getMessage()+"}";
		response.getWriter().print(error);
		ex.printStackTrace();
	}
} 
```

**Comment by dasguptahirak** [comment]
@abhijit-mishra2003 
Please add following line:
String listData = 
			"{\"Result\":\"OK\",\"Record\":" + 
			"{\"App_ID\":1,\"APP_NAME\":\"3PLA\",\"APP_ACRONYM\":\"3PLA\",\"QMGR\":\"FFLGE1CU06\",\"Primary_server\":\"ausul1mqa04.us.dell.com\",\"Secondary_server\":\"ausul1mqb04.us.dell.com\",\"OS_TYPE\":\"OEL\",\"Client_Version\":\"7.5.0.5\",\"APP_TECHNOLOGY\":\"Java\",\"VERSION\":\"1.7\",\"REGION\":\"DAO\"}" + 
			"}";
response.setContentType("application/json");
response.getWriter().print(listData);

**Comment by abhijit-mishra2003** [comment]
I did the changes, still get "No data available!"
Request you to remove the hostnames from the JSON. My bad I forgot to mask them. I'll post the full code soon. Thanks in advance.

**Comment by dasguptahirak** [comment]
Kindly refer below url

http://www.programming-free.com/2013/07/setup-load-data-jtable-jsp-servlet.html

**Comment by abhijit-mishra2003** [comment]
@dasguptahirak 

Thanks for taking time out to help me. This sample code is actually based on the URL that you have  referred. As I said, the parent table loads without any issue. Its only the child table which still does not work.

Here is the final code 
**Servlet**
```
	String acronym=null, envDropDown=null;
	if(request.getParameter("selectEnv")!=null && !request.getParameter("selectEnv").isEmpty()){  envDropDown=(String)request.getParameter("selectEnv"); }
	if(request.getParameter("apps_id")!=null){apps_id= Integer.parseInt(request.getParameter("apps_id") ); } 

	try{						
	AppDetails appMq=dao.getAppsByAppIdEnv(apps_id, envDropDown);
	JsonElement element = gson.toJsonTree(appMq, new TypeToken<AppDetails>() {}.getType());
	
	String listData=element.toString();				
	listData= "{\"Result\":\"OK\",\"Record\":"  +listData+"}";
	response.setContentType("application/json");
	System.out.println(listData);
	response.getWriter().print(listData);
	}catch(Exception ex){
		String error="{\"Result\":\"ERROR\",\"Message\":"+ex.getMessage()+"}";
		response.getWriter().print(error);
		ex.printStackTrace();
	}	
```
**JS**

```
	$img.click(function () {
		$('#MQReposTable').jtable('openChildTable',
				$img.closest('tr'),
				{
					title: app.record.APP_NAME + ' - Details',
					actions: 
					{
						listAction: 'CRUDController?action=getAppsByAppIdEnv?apps_id='+ app.record.App_ID + "&selectEnv="+$('#selectEnv').val(),
						deleteAction: 'CRUDController?action=DelAppsByAppIdEnv?apps_id='+ app.record.App_ID,
						updateAction: 'CRUDController?action=updAppsByAppIdEnv?apps_id='+ app.record.App_ID,
						createAction: 'CRUDController?action=crtAppsByAppIdEnv?apps_id=' + app.record.App_ID
					},
					fields: 
					{
						App_ID:   {title:'App ID', key: true,list: true,create:true,width: '5px'},
						APP_NAME: {title:'APP_NAME',width: '12px',edit: true},
						MQ_CLIENT_VERSION:{title:'MQ Client Ver',width: '12px',edit: true}
//                  
					} 
				
			  }, 
			  function (data) { //opened handler
					data.childTable.jtable('load');
		});
	});
	//Return image to show on the person row
	return $img;
```

JSON response to 'listAction: 'CRUDController?action=getAppsByAppIdEnv?apps_id='+ app.record.App_ID + "&selectEnv="+$('#selectEnv').val(),'

`{"Result":"OK","Record":{"App_ID":3,"APP_ACRONYM":"ASN DASHBOARD","APP_NAME":"ASN DASHBOARD","APP_TECHNOLOGY":"Java","APP_VERSION":"1.7","QMGR":"ABC","MQ_CLIENT_VERSION":"7.5.0.5","XA_ENABLED":false,"Recon_Logic":false,"CHLAUTH":false}}`

Even though I get the proper JSON data, even after setting CetContentType("application/json"), it still does not load the tables.

One more request, **please delete your response where I have put server details**. I forgot to mask it. It would be security violation from my side. Appreciate your help.

**Comment by dasguptahirak** [comment]
@abhijit-mishra2003 
Sure I will delete the server details.
I got the bug:
you have to change "Record" to "Records" in JSON
{"Result":"OK","**Records**":{"App_ID":3,"APP_ACRONYM":"ASN DASHBOARD","APP_NAME":"ASN DASHBOARD","APP_TECHNOLOGY":"Java","APP_VERSION":"1.7","QMGR":"ABC","MQ_CLIENT_VERSION":"7.5.0.5","XA_ENABLED":false,"Recon_Logic":false,"CHLAUTH":false}}

**Comment by abhijit-mishra2003** [comment]
@dasguptahirak 
Dont you think "Records" is for array? When I change it to "Result":"OK","Records": , I get same number of blank lines as number of elements in the retrieved record. When I use only "Record" I get 1 blank line saying "No Data available".

"Result":"OK","Record":
![with_record](https://user-images.githubusercontent.com/35542863/36421581-08c45a92-165f-11e8-9339-5defde8f3103.JPG)
 
"Result":"OK","Records":
![with_records](https://user-images.githubusercontent.com/35542863/36421609-251be070-165f-11e8-87f1-4d1cd306ef17.JPG)


So still stuck :)

**Comment by dasguptahirak** [comment]
Ok 

I Think in JSON format it should be "Records" with square brakets [] like this:

{
 "Result":"OK",
 **"Records":[**
  {"PersonId":1,"Name":"Benjamin Button","Age":17,"RecordDate":"\/Date(1320259705710)\/"},
  {"PersonId":2,"Name":"Douglas Adams","Age":42,"RecordDate":"\/Date(1320259705710)\/"},
  {"PersonId":3,"Name":"Isaac Asimov","Age":26,"RecordDate":"\/Date(1320259705710)\/"},
  {"PersonId":4,"Name":"Thomas More","Age":65,"RecordDate":"\/Date(1320259705710)\/"}
 **]**
}

**Comment by abhijit-mishra2003** [comment]
@dasguptahirak 
Thats for array with multiple records. Here I'm sending only 1 record with multiple elements for the child table. So I have used "**Record**" rather than "**Records**".

Also request you to please edit or delete your comment with the server names. Its quite important for me.

**Comment by abhijit-mishra2003** [comment]
@hikalkan 
Am I right? Should I be using "Record" for single record?

**Comment by dasguptahirak** [comment]
@abhijit
"Record" is used in create and edit Actions
because we can create and edit record only one at a time.
But in list "Records" should be used.

@hikalkan 
Please clarify

**Comment by abhijit-mishra2003** [comment]
Oh that fixed it @dasguptahirak .. It worked with Records and so had to add [] to make it an array.

Here is the final JSON that worked for me.

```
{	
	"Result":"OK",
	"Records":
	[
		{"App_ID1":1,"APP_NAME1":"ABC","APP_ACRONYM1":"ABC","QMGR":"ABC","APP_TECHNOLOGY":"Java","VERSION":"1.7","REGION":"ABC"}
	]
}
```
Since I assumed it to be a single record, I never made it **"Records"** and was passing it as a single Record. After I made it Records and wrapped it with in [ ] it worked.

Thanks a log for your time and patience. Appreciate your help. 👍

**Comment by dasguptahirak** [comment]
Welcome @abhijit
I am glad that it worked 😊
