### ISSUE TITLE
defaultSorting with Multiple Columns

### ISSUE THREAD

**Issue by HammerData** [hikalkan/jtable#2153]
I was running into the issue where defaultSorting was a problem  (#1484 ) if I sorted by something like **parent_id** and I also had a field called **id**. I implemented the fix in the referenced issue. It worked, but broke specifying multiple fields in defaultSorting, i.e. **defaultSorting: 'state ASC, city ASC, name ASC'** 

Is there a fix for the fix?

**Comment by dasguptahirak** [comment]
@HammerData 
Kindly have a look on following url
http://www.jtable.org/demo/pagingandsorting

**jtSorting**: A string which represents requested sorting. It is built from sorting field name plus sorting direction. For instance, It can be 'Name ASC', 'BirtDate DESC', 'Age ASC'... etc.

**jtSorting**="Name ASC', 'BirtDate DESC"

You can create getter and setter for **jtSorting** in Struts Action/Controller and then parse **jtSorting** using String Tokenizer like this:

` String[] temp;
/* delimiter */
  String delimiter = " |,";
if(!jtSorting.equals(""))
	         {
	         temp = jtSorting.split(delimiter);
	         
	         for(int i=0;i<temp.length;i++)
	         {
	         
	         if(temp[i].equals("ASC"))
	         {
	        	 crit.addOrder(Order.asc(temp[i-1]));
	         }
	         else if(temp[i].equals("DESC"))
	         {
	        	 crit.addOrder(Order.desc(temp[i-1]));	 
	         }
	         }
	         }
`
I have used Hibernate criteria so "crit" is object of my Hibernate criteria

**Comment by HammerData** [comment]
Thanks for pointing me in the right direction, @dasguptahirak! A bit of debug in the right place reveals that the fix is a lot easier than that. I just needed to take the spaces out of the list. The routine that splits the defaultSorting option isn't trimming the values, so the extra whitespace was throwing off the field name comparisons. It has to be **defaultSorting: 'state ASC,city ASC,name ASC'** without spaces after the commas.
