### ISSUE TITLE
How to display dynamic text in jtable toolbar

### ISSUE THREAD

**Issue by nkvls** [hikalkan/jtable#2164]
Hi, 
I want to show some dynamic text to display in toolbar which is coming from server. The text is repeating for all rows (from server) so I just need to pick the top row to get the data to display. I've found that jtable do not support display function (just like we do in fields). 
How can I achieve this? Below is sample code (display doesn't work though)...

toolbar: {
                items: [{
                    text: '<b>Last Received Date: </b>',
                    display: function(data){
                        $.each($('#playlistSearchTableContainer .jtable-data-row'), function () {
                            var ele = $(this);
                            var data = ele.data('record');
                            data.LastReceivedOn;
                        });
                    }
                    }]

**Comment by misterparsons** [comment]
Your problem arises because the toolbar item is constructed when the jTable is created, which is before the content is loaded. You will need to place some static text in the toolbar item when the jTable is created, then use the the recordsLoaded event to update it one the content is loaded.

Your jtable definition will look a bit like

        toolbar: {
    	    items[{
    		text: 'Last Received Date:'
    	    }]
        },
        fields: {
        },
        recordsLoaded: function (event, data) {
    	    $('#playlistSearchTableContainer span.jtable-toolbar-item-text:contains('Last Received Date:'))
    	        .text('last Received Date: ' + data.records[0].LastReceivedOn);
        }

**Comment by nkvls** [comment]
Excellent. I think that's the way it can be. Thank you very much. Closing this issue
