### ISSUE TITLE
jTable - Child table not showing records.

### ISSUE THREAD

**Issue by elpepefontana** [hikalkan/jtable#2182]
My jtable suddenly stoped to show child records.
The ajax response is OK, but the records ara not loaded.

{"Result":"OK","TotalRecordCount":2,"Records":[{"id":"4","id_tabla":"2","nombre":"nombre","etiqueta":"nombre","tipo":"VARCHAR","longitud":"150","nulo":"0","indice":"No","autoincremental":"0","mostrar":"1","clave":"0","buscable":"1"},{"id":"5","id_tabla":"2","nombre":"fecha","etiqueta":"fecha","tipo":"DATETIME","longitud":"0","nulo":"1","indice":"No","autoincremental":"0","mostrar":"1","clave":"1","buscable":"0"}]}

Jtable:

`<div id="Tablas" style=""></div>
...........................
<script type="text/javascript">
    $(document).ready(function () {
        $('#Tablas').jtable({
            title: 'Tablas',
            create: true,
            paging: true,
            pageSize: 25, 
            sorting: true,     
            jtStartIndex: 1,     
            jtPageSize: 25, 
            jtSorting: 'nombre ASC',
            defaultSorting: 'nombre ASC',
            actions: {
                listAction: function (postData, jtParams) {
                                return $.Deferred(function ($dfd) {
                                $.ajax({
                                    url: 'Tablas/AccionesTablas.php?action=listar&jtStartIndex=' + jtParams.jtStartIndex + '&jtPageSize=' + jtParams.jtPageSize + '&jtSorting=' + jtParams.jtSorting,
                                    type: 'POST',
                                    dataType: 'json',
                                    data: postData,
                                    success: function (data) {
                                        $dfd.resolve(data);
                                    },
                                    error: function () {
                                        $dfd.reject();
                                    }
                                    });
                                });
                            },
                createAction: 'Tablas/AccionesTablas.php?action=crear',
                updateAction: 'Tablas/AccionesTablas.php?action=actualizar',
                deleteAction: 'Tablas/AccionesTablas.php?action=borrar'
            },
            fields: { 
                id: {key: true,list: false},
                columnas: {
                    title: '#',
                    width: '1%',
                    sorting: true,
                    edit: false,
                    create: false,
                    paging: false,
                    display: function (tableData) {                         
                            var $img = $('<span class="mif-list2"></span>');                         
                            $img.click(function () {
                                parentTable = $("#Tablas");
                                var tr = $(this).parents("tr");
                                isChildRowOpen = parentTable.jtable("isChildRowOpen", tr );                
                                if(isChildRowOpen){
                                    $(parentTable.jtable("getChildRow", tr)).slideUp();
                                    return;
                                };
                                $('#Tablas').jtable('openChildTable',
                                    $img.closest('tr'),
                                    {
                                        title: tableData.record.nombre + ' - Columnas',
                                        actions: {
                                            listAction:   'Columnas/AccionesColumnas.php?action=listar&idtabla=' + tableData.record.id,
                                            deleteAction: 'Columnas/AccionesColumnas.php?action=borrar',
                                            updateAction: 'Columnas/AccionesColumnas.php?action=actualizar',
                                            createAction: 'Columnas/AccionesColumnas.php?action=crear&idtabla=' + tableData.record.id
                                        },
                                        fields: {
                                            id: {key: true,list: false},
                                            nombre: {title: 'Nombre',width: '10%'},
                                            etiqueta: {title: 'Etiqueta',width: '10%'},
                                            tipo: { title: 'Tipo',width: '10%', options: {'INTEGER': 'INTEGER', 'DECIMAL': 'DECIMAL', 'FLOAT': 'FLOAT', 'DATE': 'DATE', 'DATETIME': 'DATETIME', 'TEXT': 'TEXT', 'VARCHAR': 'VARCHAR'} },
                                            longitud: {title: 'Longitud', width: '10%'},
                                            nulo: { title: 'Nulo', width: '10%',type: 'checkbox',values: {'0': 'No', '1': 'Si'},defaultValue: '1' },
                                            indice: { title: 'Indice', options: {'No': 'No', 'PRIMARY': 'PRIMARY', 'UNIQUE': 'UNIQUE'} },
                                            autoincremental: {title: 'Autoincremental?', width: '10%', type: 'checkbox', values:{'0': 'No', '1': 'Si'}, defaultValue: '1'}, 
                                            mostrar: {title: 'Mostrar?', width: '10%', type: 'checkbox', values: {'0': 'No', '1': '1'}, defaultValue: '1'},
                                            clave:{title: 'Clave?', width: '10%', type: 'checkbox', value: {'0': 'No', '1': 'si'}, defaultValue: '1'},
                                            buscable:{title: 'Buscable?', width: '10%', type: 'checkbox', value: {'0': 'No', '1': 'si'}, defaultValue: '1'}
                                        }
                                    }, function (data) {
                                        data.childTable.jtable('load');
                                    }); 
                                });
                            return $img;
                        }
                    }, 
                nombre: {title: 'Nombre', width: '10%'},
                editable: { title: 'Editable?', width: '10%', type: 'checkbox',values: { '0': 'No', '1': 'Si' },defaultValue: '1'},
                crear: { title: 'Crear?', width: '10%', type: 'checkbox',values: { '0': 'No', '1': 'Si' },defaultValue: '1'},
                paginacionGeneral: { title: 'Paginacion general?', width: '10%', type: 'checkbox',values: { '0': 'No', '1': 'Si' },defaultValue: '1'},
                ordenamientoGeneral: { title: 'Ordenamiento general?', width: '10%', type: 'checkbox',values: { '0': 'No', '1': 'Si' },defaultValue: '1'},
                ordenamientoDefault: { title: 'Ordenamiento default', width: '10%'},
                indiceInicio: {title: 'Indice de inicio',width: '10%'},
                tamanoPagina: {title: 'Tamano pagina', width:'10%'},
                hijosAcordion: {title: 'Hijos en acordion?', width: '5%', type: 'checkbox', values:{'0': 'No', '1': 'Si'}, defaultvalue:'1'},
                hijosOrdenamiento: {title: 'Hijos ordenamiento', width: '5%'}
            }         
        });
        $('#Tablas').jtable('load');
    });
</script>`

This is the result.

![image](https://user-images.githubusercontent.com/2715358/44820888-58b78b00-abc9-11e8-8595-84f8400388c4.png)

**Comment by elpepefontana** [comment]
form the chrome console i get this error:

Uncaught TypeError: Cannot read property '0' of undefined
    at e.(anonymous function).(anonymous function)._getCheckBoxTextForFieldByValue (http://localhost/Code%20Generator/config/librarys/jquery/jtable/jquery.jtable.min.js:67:328)
    at e.(anonymous function).(anonymous function)._getDisplayTextForRecordField (http://localhost/Code%20Generator/config/librarys/jquery/jtable/jquery.jtable.min.js:43:13)
    at e.(anonymous function).(anonymous function)._getDisplayTextForRecordField (http://localhost/Code%20Generator/config/librarys/jquery/jquery%20ui/jquery-ui.min.js:6:7987)
    at e.(anonymous function).(anonymous function)._createCellForRecordField (http://localhost/Code%20Generator/config/librarys/jquery/jtable/jquery.jtable.min.js:38:81)
    at e.(anonymous function).(anonymous function).<anonymous> (http://localhost/Code%20Generator/config/librarys/jquery/jquery%20ui/jquery-ui.min.js:6:7987)
    at e.(anonymous function).(anonymous function)._createCellForRecordField (http://localhost/Code%20Generator/config/librarys/jquery/jtable/jquery.jtable.min.js:143:12)
    at e.(anonymous function).(anonymous function)._addCellsToRowUsingRecord (http://localhost/Code%20Generator/config/librarys/jquery/jtable/jquery.jtable.min.js:37:416)
    at e.(anonymous function).(anonymous function).<anonymous> (http://localhost/Code%20Generator/config/librarys/jquery/jquery%20ui/jquery-ui.min.js:6:7987)
    at e.(anonymous function).(anonymous function)._addCellsToRowUsingRecord (http://localhost/Code%20Generator/config/librarys/jquery/jtable/jquery.jtable.min.js:87:96)
    at e.(anonymous function).(anonymous function)._addCellsToRowUsingRecord (http://localhost/Code%20Generator/config/librarys/jquery/jtable/jquery.jtable.min.js:100:362)

**Comment by elpepefontana** [comment]
```javascript
  $(document).ready(function () {
        $('#Tablas').jtable({
            title: '<?=$title;?>',
            create: <?=$create;?>,
            paging: <?=$paging;?>,
            pageSize: <?=$pageSize;?>, 
            sorting: <?=$sorting;?>,     
            jtStartIndex: <?=$jtStartIndex;?>,     
            jtPageSize: <?=$jtPageSize;?>, 
            jtSorting: '<?=$jtSorting;?>',
            defaultSorting: '<?=$defaultSorting;?>',
            actions: {
                listAction: function (postData, jtParams) {
                                return $.Deferred(function ($dfd) {
                                $.ajax({
                                    url: '<?=HOME?>/CodeGen/returnTablesJson/action=select&jtStartIndex=<?=$jtStartIndex?>&jtPageSize=<?=$jtPageSize?>&jtSorting=<?=$jtSorting?>',
                                    type: 'POST',
                                    dataType: 'json',
                                    data: postData,
                                    success: function (data) {
                                        $dfd.resolve(data);
                                    },
                                    error: function () {
                                        $dfd.reject();
                                    }
                                    });
                                });
                            },
                createAction: '<?=HOME?>/CodeGen/returnTablesJson/action=insert',
                updateAction: '<?=HOME?>/CodeGen/returnTablesJson/action=update',
                deleteAction: '<?=HOME?>/CodeGen/returnTablesJson/action=delete'
            },
            fields: { 
                id: {key: true,list: false},
                columnas: {
                    title: '#',
                    width: '1%',
                    sorting: true,
                    edit: false,
                    create: false,
                    paging: false,
                    display: function (data) {                         
                            var $img = $('<span class="mif-list2"></span>');                         
                            $img.click(function () {
                                parentTable = $("#Tablas");
                                var tr = $(this).parents("tr");
                                isChildRowOpen = parentTable.jtable("isChildRowOpen", tr );                
                                if(isChildRowOpen){
                                    $(parentTable.jtable("getChildRow", tr)).slideUp();
                                    return;
                                };
                                $('#Tablas').jtable('openChildTable',
                                    $img.closest('tr'),
                                    {
                                        title: data.record.nombre + ' - Columnas',
                                        actions: {
                                            listAction:   '<?=HOME?>/CodeGen/returnColumnsJson/action=select&idtabla=' + data.record.id,
                                            deleteAction: '<?=HOME?>/CodeGen/returnColumnsJson/action=insert',
                                            updateAction: '<?=HOME?>/CodeGen/returnColumnsJson/action=update',
                                            createAction: '<?=HOME?>/CodeGen/returnColumnsJson/action=delete&idtabla=' + data.record.id
                                        },
                                        fields: {
                                            id: {key: true,list: false},
                                            nombre: {title: 'Nombre',width: '10%'},
                                            etiqueta: {title: 'Etiqueta',width: '10%'},
                                            tipo: { title: 'Tipo',width: '10%', options: {'INTEGER': 'INTEGER', 'DECIMAL': 'DECIMAL', 'FLOAT': 'FLOAT', 'DATE': 'DATE', 'DATETIME': 'DATETIME', 'TEXT': 'TEXT', 'VARCHAR': 'VARCHAR'} },
                                            longitud: {title: 'Longitud', width: '10%'},
                                            nulo: { title: 'Nulo', width: '10%',type: 'checkbox',values: {'0': 'No', '1': 'Si'},defaultValue: '1' },
                                            indice: { title: 'Indice', options: {'No': 'No', 'PRIMARY': 'PRIMARY', 'UNIQUE': 'UNIQUE'} },
                                            autoincremental: {title: 'Autoincremental?', width: '10%', type: 'checkbox', values:{'0': 'No', '1': 'Si'}, defaultValue: '1'}, 
                                            mostrar: {title: 'Mostrar?', width: '10%', type: 'checkbox', values: {'0': 'No', '1': '1'}, defaultValue: '1'},
                                            clave:{title: 'Clave?', width: '10%', type: 'checkbox', value: {'0': 'No', '1': 'si'}, defaultValue: '1'},
                                            buscable:{title: 'Buscable?', width: '10%', type: 'checkbox', value: {'0': 'No', '1': 'si'}, defaultValue: '1'}
                                        }
                                    }, function (data) {
                                        data.childTable.jtable('load');
                                    }); 
                                });
                            return $img;
                        }
                    }, 
                nombre: {title: 'Nombre', width: '10%'},
                editable: { title: 'Editable?', width: '10%', type: 'checkbox',values: { '0': 'No', '1': 'Si' },defaultValue: '1'},
                crear: { title: 'Crear?', width: '10%', type: 'checkbox',values: { '0': 'No', '1': 'Si' },defaultValue: '1'},
                paginacionGeneral: { title: 'Paginacion general?', width: '10%', type: 'checkbox',values: { '0': 'No', '1': 'Si' },defaultValue: '1'},
                ordenamientoGeneral: { title: 'Ordenamiento general?', width: '10%', type: 'checkbox',values: { '0': 'No', '1': 'Si' },defaultValue: '1'},
                ordenamientoDefault: { title: 'Ordenamiento default', width: '10%'},
                indiceInicio: {title: 'Indice de inicio',width: '10%'},
                tamanoPagina: {title: 'Tamano pagina', width:'10%'},
                hijosAcordion: {title: 'Hijos en acordion?', width: '5%', type: 'checkbox', values:{'0': 'No', '1': 'Si'}, defaultvalue:'1'},
                hijosOrdenamiento: {title: 'Hijos ordenamiento', width: '5%'}
            }         
        });
        $('#Tablas').jtable('load');
    });
```

**Comment by elpepefontana** [comment]
Thanks a lot, you saved me.
Finally.
I've change 'value' with 'values' and it worked.
Thank you very much.

**Comment by falwickster** [comment]
@elpepefontana glad that it worked :) you can close this issue

**Comment by elpepefontana** [comment]
Thanks a lot
