### ISSUE TITLE
Question about the jtable source code

### ISSUE THREAD

**Issue by nishantgupta01** [hikalkan/jtable#2185]
I am reviewing the source code for the jtable at [jtable](https://github.com/hikalkan/jtable/blob/master/lib/jquery.jtable.js)

Is there a source code walkthrough or something? I have 1 question. 

i see a callback method being called , but i don't see where the function is defined. the function is completeCallback(). 

Can somebody help me?

**Comment by falwickster** [comment]
@nishantgupta01 Please check this for reference:

http://jtable.org/ApiReference/Methods#met-load

**completeCallback** is not defined in the library source code. It is passed by you as an optional parameter when you are using 'load' and 'reload' methods. It can be an object which will be passed to the postData or it can be a function which will be executed when data will be successfully loaded

**Comment by nishantgupta01** [comment]
Thanks
