### ISSUE TITLE
selectedRows returns different columns order 

### ISSUE THREAD

**Issue by habi3000** [hikalkan/jtable#2186]
Hello, 
The returned data from selectedRows has a different columns order than the displayed data! 
How can I fix this??

**Comment by misterparsons** [comment]
The value returned from selectedRow is the record received from the server which can have the fields in a different order to the jTable definition. The record fields are addressable by name so why is the order of fields important? If really important, change the order on the server, or use a deferred function as the listAction and re-order the fields as descried, before returning them to jTable.

**Comment by habi3000** [comment]
OK, great thanks a lot.
