### ISSUE TITLE
How to change the default shown columns

### ISSUE THREAD

**Issue by habi3000** [hikalkan/jtable#2190]
Hello, 
The table I am working on has lots of columns, +20. So I want to change the columns shown by default, to show only the required ones. But also give the user the ability to show any of the reset if he needs. 
Is this possible ??

**Comment by falwickster** [comment]
Hi @habi3000 

You can programmatically change column visibility with this:

http://www.jtable.org/ApiReference/Methods#met-changeColumnVisibility

But you will have to create UI Control (e. g. ComboBox) which toggles visibility by yourself

**Comment by habi3000** [comment]
Hello @falwickster, this is exactly what i am looking for. thanks a lot. wish you the best.
