### ISSUE TITLE
Column header does not grow vertically when content is greater than 1 line

### ISSUE THREAD

**Issue by maratlevit** [hikalkan/jtable#419]
As you can see from the screenshot below if the column header text is too big to fit inside the column header it wraps around but the column header itself remains the same size.

Please allow the column header to auto resize depending on the content.

![Screen Shot 2013-03-19 at 2 34 11 PM](https://f.cloud.github.com/assets/2008680/274019/e9c9966a-9045-11e2-9084-19e2af53847f.png)

Thanks,

Marat

**Comment by dasguptahirak** [comment]
@toomuchcoffeecoder 
Thanks for your suggestion.
But please tell me where should I write that piece of code?

div.jtable-column-header-container {height: auto !important;}
