### ISSUE TITLE
hidden input value is not submitted in update dialog

### ISSUE THREAD

**Issue by anurat** [hikalkan/jtable#987]
When I add random number to hidden input, it is not added to the edit dialog. i.e.
ins_id: {
   type: 'hidden',
   defaultValue: 1
}

the edit dialog will contain an element for ins_id with null. When I look at the code, the value for each field is retrieved from a record and since ins_id is not in a record, the value is not retrieved and defaultValue is not used.

**Comment by stiz1981** [comment]
same problem

**Comment by stiz1981** [comment]
https://github.com/hikalkan/jtable/issues/1635

**Comment by anurat** [comment]
Cool, Thank you!
I hope the fix will be in the next version of jTable.
